# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.registration_api import RegistrationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRegistrationApi(unittest.TestCase):
    """RegistrationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.registration_api.RegistrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_register_portfolio_user(self):
        """Test case for register_portfolio_user

        Register Portfolio User  # noqa: E501
        """
        pass

    def test_register_user(self):
        """Test case for register_user

        Register User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
