# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dlxapi
from dlxapi.api.ui_settings_api import UiSettingsApi  # noqa: E501
from dlxapi.rest import ApiException


class TestUiSettingsApi(unittest.TestCase):
    """UiSettingsApi unit test stubs"""

    def setUp(self):
        self.api = UiSettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_ui_settings(self):
        """Test case for delete_ui_settings

        Deletes user UI settings  # noqa: E501
        """
        pass

    def test_get_ui_settings(self):
        """Test case for get_ui_settings

        Gets user UI settings  # noqa: E501
        """
        pass

    def test_update_ui_settings(self):
        """Test case for update_ui_settings

        Updates user UI settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
