# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_locked_updated_event import UserLockedUpdatedEvent  # noqa: E501
from swagger_client.rest import ApiException


class TestUserLockedUpdatedEvent(unittest.TestCase):
    """UserLockedUpdatedEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserLockedUpdatedEvent(self):
        """Test UserLockedUpdatedEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_locked_updated_event.UserLockedUpdatedEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
