# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dlxapi
from dlxapi.api.charts_api import ChartsApi  # noqa: E501
from dlxapi.rest import ApiException


class TestChartsApi(unittest.TestCase):
    """ChartsApi unit test stubs"""

    def setUp(self):
        self.api = ChartsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_copy_charts(self):
        """Test case for copy_charts

        Copy chart configurations to another source  # noqa: E501
        """
        pass

    def test_create_chart(self):
        """Test case for create_chart

        Create chart configuration  # noqa: E501
        """
        pass

    def test_delete_chart(self):
        """Test case for delete_chart

        Delete chart configuration  # noqa: E501
        """
        pass

    def test_delete_snapshot_charts(self):
        """Test case for delete_snapshot_charts

        Delete the captured charts for a portfolio snapshot  # noqa: E501
        """
        pass

    def test_get_chart(self):
        """Test case for get_chart

        Get chart configuration by ID  # noqa: E501
        """
        pass

    def test_get_chart_data(self):
        """Test case for get_chart_data

        Get computed chart data  # noqa: E501
        """
        pass

    def test_get_chart_data_for_config(self):
        """Test case for get_chart_data_for_config

        Get computed chart data from a chart config supplied in the request body  # noqa: E501
        """
        pass

    def test_get_chart_source_structure(self):
        """Test case for get_chart_source_structure

        Get data source structure  # noqa: E501
        """
        pass

    def test_get_charts(self):
        """Test case for get_charts

        List chart configurations  # noqa: E501
        """
        pass

    def test_update_chart(self):
        """Test case for update_chart

        Updates a chart configuration utilizing JSON Patch Operations.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
