/**
 * Decision Lens API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DecisionLensApi);
  }
}(this, function(expect, DecisionLensApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DecisionLensApi.MinifiedProjects();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MinifiedProjects', function() {
    it('should create an instance of MinifiedProjects', function() {
      // uncomment below and update the code to test MinifiedProjects
      //var instance = new DecisionLensApi.MinifiedProjects();
      //expect(instance).to.be.a(DecisionLensApi.MinifiedProjects);
    });

    it('should have the property fidx (base name: "fidx")', function() {
      // uncomment below and update the code to test the property fidx
      //var instance = new DecisionLensApi.MinifiedProjects();
      //expect(instance).to.be();
    });

    it('should have the property tidx (base name: "tidx")', function() {
      // uncomment below and update the code to test the property tidx
      //var instance = new DecisionLensApi.MinifiedProjects();
      //expect(instance).to.be();
    });

    it('should have the property uidx (base name: "uidx")', function() {
      // uncomment below and update the code to test the property uidx
      //var instance = new DecisionLensApi.MinifiedProjects();
      //expect(instance).to.be();
    });

    it('should have the property prs (base name: "prs")', function() {
      // uncomment below and update the code to test the property prs
      //var instance = new DecisionLensApi.MinifiedProjects();
      //expect(instance).to.be();
    });

    it('should have the property tot (base name: "tot")', function() {
      // uncomment below and update the code to test the property tot
      //var instance = new DecisionLensApi.MinifiedProjects();
      //expect(instance).to.be();
    });

    it('should have the property lim (base name: "lim")', function() {
      // uncomment below and update the code to test the property lim
      //var instance = new DecisionLensApi.MinifiedProjects();
      //expect(instance).to.be();
    });

    it('should have the property ofs (base name: "ofs")', function() {
      // uncomment below and update the code to test the property ofs
      //var instance = new DecisionLensApi.MinifiedProjects();
      //expect(instance).to.be();
    });

  });

}));
