# Decision Lens API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' FieldIsFieldTypeApprovedUpdatedEvent Class
#'
#' @field id 
#' @field name 
#' @field isFieldTypeApproved 
#' @field previousIsFieldTypeApproved 
#' @field portfolioId 
#' @field portfolioPlan 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FieldIsFieldTypeApprovedUpdatedEvent <- R6::R6Class(
  'FieldIsFieldTypeApprovedUpdatedEvent',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `isFieldTypeApproved` = NULL,
    `previousIsFieldTypeApproved` = NULL,
    `portfolioId` = NULL,
    `portfolioPlan` = NULL,
    initialize = function(`id`, `name`, `isFieldTypeApproved`, `previousIsFieldTypeApproved`, `portfolioId`, `portfolioPlan`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`isFieldTypeApproved`)) {
        self$`isFieldTypeApproved` <- `isFieldTypeApproved`
      }
      if (!missing(`previousIsFieldTypeApproved`)) {
        self$`previousIsFieldTypeApproved` <- `previousIsFieldTypeApproved`
      }
      if (!missing(`portfolioId`)) {
        stopifnot(is.character(`portfolioId`), length(`portfolioId`) == 1)
        self$`portfolioId` <- `portfolioId`
      }
      if (!missing(`portfolioPlan`)) {
        stopifnot(R6::is.R6(`portfolioPlan`))
        self$`portfolioPlan` <- `portfolioPlan`
      }
    },
    toJSON = function() {
      FieldIsFieldTypeApprovedUpdatedEventObject <- list()
      if (!is.null(self$`id`)) {
        FieldIsFieldTypeApprovedUpdatedEventObject[['id']] <- self$`id`
      }
      if (!is.null(self$`name`)) {
        FieldIsFieldTypeApprovedUpdatedEventObject[['name']] <- self$`name`
      }
      if (!is.null(self$`isFieldTypeApproved`)) {
        FieldIsFieldTypeApprovedUpdatedEventObject[['isFieldTypeApproved']] <- self$`isFieldTypeApproved`
      }
      if (!is.null(self$`previousIsFieldTypeApproved`)) {
        FieldIsFieldTypeApprovedUpdatedEventObject[['previousIsFieldTypeApproved']] <- self$`previousIsFieldTypeApproved`
      }
      if (!is.null(self$`portfolioId`)) {
        FieldIsFieldTypeApprovedUpdatedEventObject[['portfolioId']] <- self$`portfolioId`
      }
      if (!is.null(self$`portfolioPlan`)) {
        FieldIsFieldTypeApprovedUpdatedEventObject[['portfolioPlan']] <- self$`portfolioPlan`$toJSON()
      }

      FieldIsFieldTypeApprovedUpdatedEventObject
    },
    fromJSON = function(FieldIsFieldTypeApprovedUpdatedEventJson) {
      FieldIsFieldTypeApprovedUpdatedEventObject <- jsonlite::fromJSON(FieldIsFieldTypeApprovedUpdatedEventJson)
      if (!is.null(FieldIsFieldTypeApprovedUpdatedEventObject$`id`)) {
        self$`id` <- FieldIsFieldTypeApprovedUpdatedEventObject$`id`
      }
      if (!is.null(FieldIsFieldTypeApprovedUpdatedEventObject$`name`)) {
        self$`name` <- FieldIsFieldTypeApprovedUpdatedEventObject$`name`
      }
      if (!is.null(FieldIsFieldTypeApprovedUpdatedEventObject$`isFieldTypeApproved`)) {
        self$`isFieldTypeApproved` <- FieldIsFieldTypeApprovedUpdatedEventObject$`isFieldTypeApproved`
      }
      if (!is.null(FieldIsFieldTypeApprovedUpdatedEventObject$`previousIsFieldTypeApproved`)) {
        self$`previousIsFieldTypeApproved` <- FieldIsFieldTypeApprovedUpdatedEventObject$`previousIsFieldTypeApproved`
      }
      if (!is.null(FieldIsFieldTypeApprovedUpdatedEventObject$`portfolioId`)) {
        self$`portfolioId` <- FieldIsFieldTypeApprovedUpdatedEventObject$`portfolioId`
      }
      if (!is.null(FieldIsFieldTypeApprovedUpdatedEventObject$`portfolioPlan`)) {
        portfolioPlanObject <- PortfolioPlan$new()
        portfolioPlanObject$fromJSON(jsonlite::toJSON(FieldIsFieldTypeApprovedUpdatedEventObject$portfolioPlan, auto_unbox = TRUE))
        self$`portfolioPlan` <- portfolioPlanObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "name": %s,
           "isFieldTypeApproved": %s,
           "previousIsFieldTypeApproved": %s,
           "portfolioId": %s,
           "portfolioPlan": %s
        }',
        self$`id`,
        self$`name`,
        self$`isFieldTypeApproved`,
        self$`previousIsFieldTypeApproved`,
        self$`portfolioId`,
        self$`portfolioPlan`$toJSON()
      )
    },
    fromJSONString = function(FieldIsFieldTypeApprovedUpdatedEventJson) {
      FieldIsFieldTypeApprovedUpdatedEventObject <- jsonlite::fromJSON(FieldIsFieldTypeApprovedUpdatedEventJson)
      self$`id` <- FieldIsFieldTypeApprovedUpdatedEventObject$`id`
      self$`name` <- FieldIsFieldTypeApprovedUpdatedEventObject$`name`
      self$`isFieldTypeApproved` <- FieldIsFieldTypeApprovedUpdatedEventObject$`isFieldTypeApproved`
      self$`previousIsFieldTypeApproved` <- FieldIsFieldTypeApprovedUpdatedEventObject$`previousIsFieldTypeApproved`
      self$`portfolioId` <- FieldIsFieldTypeApprovedUpdatedEventObject$`portfolioId`
      PortfolioPlanObject <- PortfolioPlan$new()
      self$`portfolioPlan` <- PortfolioPlanObject$fromJSON(jsonlite::toJSON(FieldIsFieldTypeApprovedUpdatedEventObject$portfolioPlan, auto_unbox = TRUE))
    }
  )
)
