# Decision Lens API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' PortfolioPlanUser Class
#'
#' @field href 
#' @field id 
#' @field createdAt 
#' @field modifiedAt 
#' @field user 
#' @field portfolioPlan 
#' @field roles 
#' @field permissions 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PortfolioPlanUser <- R6::R6Class(
  'PortfolioPlanUser',
  public = list(
    `href` = NULL,
    `id` = NULL,
    `createdAt` = NULL,
    `modifiedAt` = NULL,
    `user` = NULL,
    `portfolioPlan` = NULL,
    `roles` = NULL,
    `permissions` = NULL,
    initialize = function(`href`, `id`, `createdAt`, `modifiedAt`, `user`, `portfolioPlan`, `roles`, `permissions`){
      if (!missing(`href`)) {
        stopifnot(is.character(`href`), length(`href`) == 1)
        self$`href` <- `href`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`createdAt`)) {
        stopifnot(is.character(`createdAt`), length(`createdAt`) == 1)
        self$`createdAt` <- `createdAt`
      }
      if (!missing(`modifiedAt`)) {
        stopifnot(is.character(`modifiedAt`), length(`modifiedAt`) == 1)
        self$`modifiedAt` <- `modifiedAt`
      }
      if (!missing(`user`)) {
        stopifnot(R6::is.R6(`user`))
        self$`user` <- `user`
      }
      if (!missing(`portfolioPlan`)) {
        stopifnot(R6::is.R6(`portfolioPlan`))
        self$`portfolioPlan` <- `portfolioPlan`
      }
      if (!missing(`roles`)) {
        stopifnot(is.list(`roles`), length(`roles`) != 0)
        lapply(`roles`, function(x) stopifnot(R6::is.R6(x)))
        self$`roles` <- `roles`
      }
      if (!missing(`permissions`)) {
        stopifnot(R6::is.R6(`permissions`))
        self$`permissions` <- `permissions`
      }
    },
    toJSON = function() {
      PortfolioPlanUserObject <- list()
      if (!is.null(self$`href`)) {
        PortfolioPlanUserObject[['href']] <- self$`href`
      }
      if (!is.null(self$`id`)) {
        PortfolioPlanUserObject[['id']] <- self$`id`
      }
      if (!is.null(self$`createdAt`)) {
        PortfolioPlanUserObject[['createdAt']] <- self$`createdAt`
      }
      if (!is.null(self$`modifiedAt`)) {
        PortfolioPlanUserObject[['modifiedAt']] <- self$`modifiedAt`
      }
      if (!is.null(self$`user`)) {
        PortfolioPlanUserObject[['user']] <- self$`user`$toJSON()
      }
      if (!is.null(self$`portfolioPlan`)) {
        PortfolioPlanUserObject[['portfolioPlan']] <- self$`portfolioPlan`$toJSON()
      }
      if (!is.null(self$`roles`)) {
        PortfolioPlanUserObject[['roles']] <- lapply(self$`roles`, function(x) x$toJSON())
      }
      if (!is.null(self$`permissions`)) {
        PortfolioPlanUserObject[['permissions']] <- self$`permissions`$toJSON()
      }

      PortfolioPlanUserObject
    },
    fromJSON = function(PortfolioPlanUserJson) {
      PortfolioPlanUserObject <- dlensFromJSON(PortfolioPlanUserJson)
      if (!is.null(PortfolioPlanUserObject$`href`)) {
        self$`href` <- PortfolioPlanUserObject$`href`
      }
      if (!is.null(PortfolioPlanUserObject$`id`)) {
        self$`id` <- PortfolioPlanUserObject$`id`
      }
      if (!is.null(PortfolioPlanUserObject$`createdAt`)) {
        self$`createdAt` <- PortfolioPlanUserObject$`createdAt`
      }
      if (!is.null(PortfolioPlanUserObject$`modifiedAt`)) {
        self$`modifiedAt` <- PortfolioPlanUserObject$`modifiedAt`
      }
      if (!is.null(PortfolioPlanUserObject$`user`)) {
        userObject <- User$new()
        userObject$fromJSON(jsonlite::toJSON(PortfolioPlanUserObject$user, auto_unbox = TRUE))
        self$`user` <- userObject
      }
      if (!is.null(PortfolioPlanUserObject$`portfolioPlan`)) {
        portfolioPlanObject <- PortfolioPlan$new()
        portfolioPlanObject$fromJSON(jsonlite::toJSON(PortfolioPlanUserObject$portfolioPlan, auto_unbox = TRUE))
        self$`portfolioPlan` <- portfolioPlanObject
      }
      if (!is.null(PortfolioPlanUserObject$`roles`)) {
        self$`roles` <- lapply(PortfolioPlanUserObject$`roles`, function(x) {
          rolesObject <- PortfolioPlanUserRole$new()
          rolesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          rolesObject
        })
      }
      if (!is.null(PortfolioPlanUserObject$`permissions`)) {
        permissionsObject <- Permissions$new()
        permissionsObject$fromJSON(jsonlite::toJSON(PortfolioPlanUserObject$permissions, auto_unbox = TRUE))
        self$`permissions` <- permissionsObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "href": %s,
           "id": %s,
           "createdAt": %s,
           "modifiedAt": %s,
           "user": %s,
           "portfolioPlan": %s,
           "roles": [%s],
           "permissions": %s
        }',
        self$`href`,
        self$`id`,
        self$`createdAt`,
        self$`modifiedAt`,
        self$`user`$toJSON(),
        self$`portfolioPlan`$toJSON(),
        lapply(self$`roles`, function(x) paste(x$toJSON(), sep=",")),
        self$`permissions`$toJSON()
      )
    },
    fromJSONString = function(PortfolioPlanUserJson) {
      PortfolioPlanUserObject <- dlensFromJSON(PortfolioPlanUserJson)
      self$`href` <- PortfolioPlanUserObject$`href`
      self$`id` <- PortfolioPlanUserObject$`id`
      self$`createdAt` <- PortfolioPlanUserObject$`createdAt`
      self$`modifiedAt` <- PortfolioPlanUserObject$`modifiedAt`
      UserObject <- User$new()
      self$`user` <- UserObject$fromJSON(jsonlite::toJSON(PortfolioPlanUserObject$user, auto_unbox = TRUE))
      PortfolioPlanObject <- PortfolioPlan$new()
      self$`portfolioPlan` <- PortfolioPlanObject$fromJSON(jsonlite::toJSON(PortfolioPlanUserObject$portfolioPlan, auto_unbox = TRUE))
      self$`roles` <- lapply(PortfolioPlanUserObject$`roles`, function(x) PortfolioPlanUserRole$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      PermissionsObject <- Permissions$new()
      self$`permissions` <- PermissionsObject$fromJSON(jsonlite::toJSON(PortfolioPlanUserObject$permissions, auto_unbox = TRUE))
    }
  )
)
