# Decision Lens API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' RecommendationType Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RecommendationType <- R6::R6Class(
  'RecommendationType',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      RecommendationTypeObject <- list()

      RecommendationTypeObject
    },
    fromJSON = function(RecommendationTypeJson) {
      RecommendationTypeObject <- jsonlite::fromJSON(RecommendationTypeJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(RecommendationTypeJson) {
      RecommendationTypeObject <- jsonlite::fromJSON(RecommendationTypeJson)
    }
  )
)
