# Decision Lens API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ResourcePoolBudgetAmountUpdatedEvent Class
#'
#' @field id 
#' @field name 
#' @field budgetAmount 
#' @field previousBudgetAmount 
#' @field timePeriod 
#' @field portfolioId 
#' @field portfolioPlan 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ResourcePoolBudgetAmountUpdatedEvent <- R6::R6Class(
  'ResourcePoolBudgetAmountUpdatedEvent',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `budgetAmount` = NULL,
    `previousBudgetAmount` = NULL,
    `timePeriod` = NULL,
    `portfolioId` = NULL,
    `portfolioPlan` = NULL,
    initialize = function(`id`, `name`, `budgetAmount`, `previousBudgetAmount`, `timePeriod`, `portfolioId`, `portfolioPlan`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`budgetAmount`)) {
        stopifnot(is.numeric(`budgetAmount`), length(`budgetAmount`) == 1)
        self$`budgetAmount` <- `budgetAmount`
      }
      if (!missing(`previousBudgetAmount`)) {
        stopifnot(is.numeric(`previousBudgetAmount`), length(`previousBudgetAmount`) == 1)
        self$`previousBudgetAmount` <- `previousBudgetAmount`
      }
      if (!missing(`timePeriod`)) {
        stopifnot(R6::is.R6(`timePeriod`))
        self$`timePeriod` <- `timePeriod`
      }
      if (!missing(`portfolioId`)) {
        stopifnot(is.character(`portfolioId`), length(`portfolioId`) == 1)
        self$`portfolioId` <- `portfolioId`
      }
      if (!missing(`portfolioPlan`)) {
        stopifnot(R6::is.R6(`portfolioPlan`))
        self$`portfolioPlan` <- `portfolioPlan`
      }
    },
    toJSON = function() {
      ResourcePoolBudgetAmountUpdatedEventObject <- list()
      if (!is.null(self$`id`)) {
        ResourcePoolBudgetAmountUpdatedEventObject[['id']] <- self$`id`
      }
      if (!is.null(self$`name`)) {
        ResourcePoolBudgetAmountUpdatedEventObject[['name']] <- self$`name`
      }
      if (!is.null(self$`budgetAmount`)) {
        ResourcePoolBudgetAmountUpdatedEventObject[['budgetAmount']] <- self$`budgetAmount`
      }
      if (!is.null(self$`previousBudgetAmount`)) {
        ResourcePoolBudgetAmountUpdatedEventObject[['previousBudgetAmount']] <- self$`previousBudgetAmount`
      }
      if (!is.null(self$`timePeriod`)) {
        ResourcePoolBudgetAmountUpdatedEventObject[['timePeriod']] <- self$`timePeriod`$toJSON()
      }
      if (!is.null(self$`portfolioId`)) {
        ResourcePoolBudgetAmountUpdatedEventObject[['portfolioId']] <- self$`portfolioId`
      }
      if (!is.null(self$`portfolioPlan`)) {
        ResourcePoolBudgetAmountUpdatedEventObject[['portfolioPlan']] <- self$`portfolioPlan`$toJSON()
      }

      ResourcePoolBudgetAmountUpdatedEventObject
    },
    fromJSON = function(ResourcePoolBudgetAmountUpdatedEventJson) {
      ResourcePoolBudgetAmountUpdatedEventObject <- jsonlite::fromJSON(ResourcePoolBudgetAmountUpdatedEventJson)
      if (!is.null(ResourcePoolBudgetAmountUpdatedEventObject$`id`)) {
        self$`id` <- ResourcePoolBudgetAmountUpdatedEventObject$`id`
      }
      if (!is.null(ResourcePoolBudgetAmountUpdatedEventObject$`name`)) {
        self$`name` <- ResourcePoolBudgetAmountUpdatedEventObject$`name`
      }
      if (!is.null(ResourcePoolBudgetAmountUpdatedEventObject$`budgetAmount`)) {
        self$`budgetAmount` <- ResourcePoolBudgetAmountUpdatedEventObject$`budgetAmount`
      }
      if (!is.null(ResourcePoolBudgetAmountUpdatedEventObject$`previousBudgetAmount`)) {
        self$`previousBudgetAmount` <- ResourcePoolBudgetAmountUpdatedEventObject$`previousBudgetAmount`
      }
      if (!is.null(ResourcePoolBudgetAmountUpdatedEventObject$`timePeriod`)) {
        timePeriodObject <- TimePeriod$new()
        timePeriodObject$fromJSON(jsonlite::toJSON(ResourcePoolBudgetAmountUpdatedEventObject$timePeriod, auto_unbox = TRUE))
        self$`timePeriod` <- timePeriodObject
      }
      if (!is.null(ResourcePoolBudgetAmountUpdatedEventObject$`portfolioId`)) {
        self$`portfolioId` <- ResourcePoolBudgetAmountUpdatedEventObject$`portfolioId`
      }
      if (!is.null(ResourcePoolBudgetAmountUpdatedEventObject$`portfolioPlan`)) {
        portfolioPlanObject <- PortfolioPlan$new()
        portfolioPlanObject$fromJSON(jsonlite::toJSON(ResourcePoolBudgetAmountUpdatedEventObject$portfolioPlan, auto_unbox = TRUE))
        self$`portfolioPlan` <- portfolioPlanObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "name": %s,
           "budgetAmount": %d,
           "previousBudgetAmount": %d,
           "timePeriod": %s,
           "portfolioId": %s,
           "portfolioPlan": %s
        }',
        self$`id`,
        self$`name`,
        self$`budgetAmount`,
        self$`previousBudgetAmount`,
        self$`timePeriod`$toJSON(),
        self$`portfolioId`,
        self$`portfolioPlan`$toJSON()
      )
    },
    fromJSONString = function(ResourcePoolBudgetAmountUpdatedEventJson) {
      ResourcePoolBudgetAmountUpdatedEventObject <- jsonlite::fromJSON(ResourcePoolBudgetAmountUpdatedEventJson)
      self$`id` <- ResourcePoolBudgetAmountUpdatedEventObject$`id`
      self$`name` <- ResourcePoolBudgetAmountUpdatedEventObject$`name`
      self$`budgetAmount` <- ResourcePoolBudgetAmountUpdatedEventObject$`budgetAmount`
      self$`previousBudgetAmount` <- ResourcePoolBudgetAmountUpdatedEventObject$`previousBudgetAmount`
      TimePeriodObject <- TimePeriod$new()
      self$`timePeriod` <- TimePeriodObject$fromJSON(jsonlite::toJSON(ResourcePoolBudgetAmountUpdatedEventObject$timePeriod, auto_unbox = TRUE))
      self$`portfolioId` <- ResourcePoolBudgetAmountUpdatedEventObject$`portfolioId`
      PortfolioPlanObject <- PortfolioPlan$new()
      self$`portfolioPlan` <- PortfolioPlanObject$fromJSON(jsonlite::toJSON(ResourcePoolBudgetAmountUpdatedEventObject$portfolioPlan, auto_unbox = TRUE))
    }
  )
)
