# Decision Lens API
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' UserAuthenticatedEvent Class
#'
#' @field id 
#' @field user 
#' @field clientId 
#' @field groupId 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserAuthenticatedEvent <- R6::R6Class(
  'UserAuthenticatedEvent',
  public = list(
    `id` = NULL,
    `user` = NULL,
    `clientId` = NULL,
    `groupId` = NULL,
    initialize = function(`id`, `user`, `clientId`, `groupId`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`user`)) {
        stopifnot(R6::is.R6(`user`))
        self$`user` <- `user`
      }
      if (!missing(`clientId`)) {
        stopifnot(is.character(`clientId`), length(`clientId`) == 1)
        self$`clientId` <- `clientId`
      }
      if (!missing(`groupId`)) {
        stopifnot(is.character(`groupId`), length(`groupId`) == 1)
        self$`groupId` <- `groupId`
      }
    },
    toJSON = function() {
      UserAuthenticatedEventObject <- list()
      if (!is.null(self$`id`)) {
        UserAuthenticatedEventObject[['id']] <- self$`id`
      }
      if (!is.null(self$`user`)) {
        UserAuthenticatedEventObject[['user']] <- self$`user`$toJSON()
      }
      if (!is.null(self$`clientId`)) {
        UserAuthenticatedEventObject[['clientId']] <- self$`clientId`
      }
      if (!is.null(self$`groupId`)) {
        UserAuthenticatedEventObject[['groupId']] <- self$`groupId`
      }

      UserAuthenticatedEventObject
    },
    fromJSON = function(UserAuthenticatedEventJson) {
      UserAuthenticatedEventObject <- dlensFromJSON(UserAuthenticatedEventJson)
      if (!is.null(UserAuthenticatedEventObject$`id`)) {
        self$`id` <- UserAuthenticatedEventObject$`id`
      }
      if (!is.null(UserAuthenticatedEventObject$`user`)) {
        userObject <- User$new()
        userObject$fromJSON(jsonlite::toJSON(UserAuthenticatedEventObject$user, auto_unbox = TRUE))
        self$`user` <- userObject
      }
      if (!is.null(UserAuthenticatedEventObject$`clientId`)) {
        self$`clientId` <- UserAuthenticatedEventObject$`clientId`
      }
      if (!is.null(UserAuthenticatedEventObject$`groupId`)) {
        self$`groupId` <- UserAuthenticatedEventObject$`groupId`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "user": %s,
           "clientId": %s,
           "groupId": %s
        }',
        self$`id`,
        self$`user`$toJSON(),
        self$`clientId`,
        self$`groupId`
      )
    },
    fromJSONString = function(UserAuthenticatedEventJson) {
      UserAuthenticatedEventObject <- dlensFromJSON(UserAuthenticatedEventJson)
      self$`id` <- UserAuthenticatedEventObject$`id`
      UserObject <- User$new()
      self$`user` <- UserObject$fromJSON(jsonlite::toJSON(UserAuthenticatedEventObject$user, auto_unbox = TRUE))
      self$`clientId` <- UserAuthenticatedEventObject$`clientId`
      self$`groupId` <- UserAuthenticatedEventObject$`groupId`
    }
  )
)
