/**
 * Decision Lens API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Attachment', 'model/Project'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Attachment'), require('./Project'));
  } else {
    // Browser globals (root is window)
    if (!root.DecisionLensApi) {
      root.DecisionLensApi = {};
    }
    root.DecisionLensApi.DraftProjectsSubmittedMessagePayload = factory(root.DecisionLensApi.ApiClient, root.DecisionLensApi.Attachment, root.DecisionLensApi.Project);
  }
}(this, function(ApiClient, Attachment, Project) {
  'use strict';




  /**
   * The DraftProjectsSubmittedMessagePayload model module.
   * @module model/DraftProjectsSubmittedMessagePayload
   * @version 1.0
   */

  /**
   * Constructs a new <code>DraftProjectsSubmittedMessagePayload</code>.
   * @alias module:model/DraftProjectsSubmittedMessagePayload
   * @class
   * @param projects {Array.<module:model/Project>} 
   */
  var exports = function(projects) {
    var _this = this;

    _this['projects'] = projects;

  };

  /**
   * Constructs a <code>DraftProjectsSubmittedMessagePayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DraftProjectsSubmittedMessagePayload} obj Optional instance to populate.
   * @return {module:model/DraftProjectsSubmittedMessagePayload} The populated <code>DraftProjectsSubmittedMessagePayload</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('projects')) {
        obj['projects'] = ApiClient.convertToType(data['projects'], [Project]);
      }
      if (data.hasOwnProperty('attachments')) {
        obj['attachments'] = ApiClient.convertToType(data['attachments'], [Attachment]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Project>} projects
   */
  exports.prototype['projects'] = undefined;
  /**
   * @member {Array.<module:model/Attachment>} attachments
   */
  exports.prototype['attachments'] = undefined;



  return exports;
}));


