/**
 * Decision Lens API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Field', 'model/FieldValues', 'model/Project', 'model/TimePeriod'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Field'), require('./FieldValues'), require('./Project'), require('./TimePeriod'));
  } else {
    // Browser globals (root is window)
    if (!root.DecisionLensApi) {
      root.DecisionLensApi = {};
    }
    root.DecisionLensApi.FieldValue = factory(root.DecisionLensApi.ApiClient, root.DecisionLensApi.Field, root.DecisionLensApi.FieldValues, root.DecisionLensApi.Project, root.DecisionLensApi.TimePeriod);
  }
}(this, function(ApiClient, Field, FieldValues, Project, TimePeriod) {
  'use strict';




  /**
   * The FieldValue model module.
   * @module model/FieldValue
   * @version 1.0
   */

  /**
   * Constructs a new <code>FieldValue</code>.
   * @alias module:model/FieldValue
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>FieldValue</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FieldValue} obj Optional instance to populate.
   * @return {module:model/FieldValue} The populated <code>FieldValue</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('field')) {
        obj['field'] = Field.constructFromObject(data['field']);
      }
      if (data.hasOwnProperty('project')) {
        obj['project'] = Project.constructFromObject(data['project']);
      }
      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'String');
      }
      if (data.hasOwnProperty('numericValue')) {
        obj['numericValue'] = ApiClient.convertToType(data['numericValue'], 'Number');
      }
      if (data.hasOwnProperty('booleanValue')) {
        obj['booleanValue'] = ApiClient.convertToType(data['booleanValue'], 'Boolean');
      }
      if (data.hasOwnProperty('numericValues')) {
        obj['numericValues'] = ApiClient.convertToType(data['numericValues'], ['Number']);
      }
      if (data.hasOwnProperty('values')) {
        obj['values'] = ApiClient.convertToType(data['values'], ['String']);
      }
      if (data.hasOwnProperty('timePeriod')) {
        obj['timePeriod'] = TimePeriod.constructFromObject(data['timePeriod']);
      }
      if (data.hasOwnProperty('details')) {
        obj['details'] = FieldValues.constructFromObject(data['details']);
      }
      if (data.hasOwnProperty('createdAt')) {
        obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
      }
      if (data.hasOwnProperty('modifiedAt')) {
        obj['modifiedAt'] = ApiClient.convertToType(data['modifiedAt'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Field} field
   */
  exports.prototype['field'] = undefined;
  /**
   * @member {module:model/Project} project
   */
  exports.prototype['project'] = undefined;
  /**
   * @member {String} value
   */
  exports.prototype['value'] = undefined;
  /**
   * @member {Number} numericValue
   */
  exports.prototype['numericValue'] = undefined;
  /**
   * @member {Boolean} booleanValue
   */
  exports.prototype['booleanValue'] = undefined;
  /**
   * @member {Array.<Number>} numericValues
   */
  exports.prototype['numericValues'] = undefined;
  /**
   * @member {Array.<String>} values
   */
  exports.prototype['values'] = undefined;
  /**
   * @member {module:model/TimePeriod} timePeriod
   */
  exports.prototype['timePeriod'] = undefined;
  /**
   * @member {module:model/FieldValues} details
   */
  exports.prototype['details'] = undefined;
  /**
   * @member {String} createdAt
   */
  exports.prototype['createdAt'] = undefined;
  /**
   * @member {String} modifiedAt
   */
  exports.prototype['modifiedAt'] = undefined;



  return exports;
}));


