/**
 * Decision Lens API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FieldType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FieldType'));
  } else {
    // Browser globals (root is window)
    if (!root.DecisionLensApi) {
      root.DecisionLensApi = {};
    }
    root.DecisionLensApi.IdeaFormFieldRequest = factory(root.DecisionLensApi.ApiClient, root.DecisionLensApi.FieldType);
  }
}(this, function(ApiClient, FieldType) {
  'use strict';




  /**
   * The IdeaFormFieldRequest model module.
   * @module model/IdeaFormFieldRequest
   * @version 1.0
   */

  /**
   * Constructs a new <code>IdeaFormFieldRequest</code>.
   * @alias module:model/IdeaFormFieldRequest
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>IdeaFormFieldRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdeaFormFieldRequest} obj Optional instance to populate.
   * @return {module:model/IdeaFormFieldRequest} The populated <code>IdeaFormFieldRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('portfolioId')) {
        obj['portfolioId'] = ApiClient.convertToType(data['portfolioId'], 'String');
      }
      if (data.hasOwnProperty('fieldIds')) {
        obj['fieldIds'] = ApiClient.convertToType(data['fieldIds'], ['String']);
      }
      if (data.hasOwnProperty('fieldTypes')) {
        obj['fieldTypes'] = ApiClient.convertToType(data['fieldTypes'], [FieldType]);
      }
      if (data.hasOwnProperty('isIncluded')) {
        obj['isIncluded'] = ApiClient.convertToType(data['isIncluded'], 'Boolean');
      }
      if (data.hasOwnProperty('isRequired')) {
        obj['isRequired'] = ApiClient.convertToType(data['isRequired'], 'Boolean');
      }
      if (data.hasOwnProperty('ideaFieldPosition')) {
        obj['ideaFieldPosition'] = ApiClient.convertToType(data['ideaFieldPosition'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} portfolioId
   */
  exports.prototype['portfolioId'] = undefined;
  /**
   * @member {Array.<String>} fieldIds
   */
  exports.prototype['fieldIds'] = undefined;
  /**
   * @member {Array.<module:model/FieldType>} fieldTypes
   */
  exports.prototype['fieldTypes'] = undefined;
  /**
   * @member {Boolean} isIncluded
   */
  exports.prototype['isIncluded'] = undefined;
  /**
   * @member {Boolean} isRequired
   */
  exports.prototype['isRequired'] = undefined;
  /**
   * @member {Number} ideaFieldPosition
   */
  exports.prototype['ideaFieldPosition'] = undefined;



  return exports;
}));


