/**
 * Decision Lens API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PortfolioPlan', 'model/ProjectFieldValue'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PortfolioPlan'), require('./ProjectFieldValue'));
  } else {
    // Browser globals (root is window)
    if (!root.DecisionLensApi) {
      root.DecisionLensApi = {};
    }
    root.DecisionLensApi.ProjectCreatedEvent = factory(root.DecisionLensApi.ApiClient, root.DecisionLensApi.PortfolioPlan, root.DecisionLensApi.ProjectFieldValue);
  }
}(this, function(ApiClient, PortfolioPlan, ProjectFieldValue) {
  'use strict';




  /**
   * The ProjectCreatedEvent model module.
   * @module model/ProjectCreatedEvent
   * @version 1.0
   */

  /**
   * Constructs a new <code>ProjectCreatedEvent</code>.
   * @alias module:model/ProjectCreatedEvent
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>ProjectCreatedEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectCreatedEvent} obj Optional instance to populate.
   * @return {module:model/ProjectCreatedEvent} The populated <code>ProjectCreatedEvent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('portfolioId')) {
        obj['portfolioId'] = ApiClient.convertToType(data['portfolioId'], 'String');
      }
      if (data.hasOwnProperty('contributingUserIds')) {
        obj['contributingUserIds'] = ApiClient.convertToType(data['contributingUserIds'], ['String']);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('isDraft')) {
        obj['isDraft'] = ApiClient.convertToType(data['isDraft'], 'Boolean');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('position')) {
        obj['position'] = ApiClient.convertToType(data['position'], 'Number');
      }
      if (data.hasOwnProperty('fieldValues')) {
        obj['fieldValues'] = ApiClient.convertToType(data['fieldValues'], [ProjectFieldValue]);
      }
      if (data.hasOwnProperty('userId')) {
        obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
      }
      if (data.hasOwnProperty('portfolioPlan')) {
        obj['portfolioPlan'] = PortfolioPlan.constructFromObject(data['portfolioPlan']);
      }
      if (data.hasOwnProperty('isFromImport')) {
        obj['isFromImport'] = ApiClient.convertToType(data['isFromImport'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} portfolioId
   */
  exports.prototype['portfolioId'] = undefined;
  /**
   * @member {Array.<String>} contributingUserIds
   */
  exports.prototype['contributingUserIds'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Boolean} isDraft
   */
  exports.prototype['isDraft'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} position
   */
  exports.prototype['position'] = undefined;
  /**
   * @member {Array.<module:model/ProjectFieldValue>} fieldValues
   */
  exports.prototype['fieldValues'] = undefined;
  /**
   * @member {String} userId
   */
  exports.prototype['userId'] = undefined;
  /**
   * @member {module:model/PortfolioPlan} portfolioPlan
   */
  exports.prototype['portfolioPlan'] = undefined;
  /**
   * @member {Boolean} isFromImport
   */
  exports.prototype['isFromImport'] = undefined;



  return exports;
}));


