/*
 * Decision Lens API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.decisionlens.client.api;

import com.decisionlens.client.ApiCallback;
import com.decisionlens.client.ApiClient;
import com.decisionlens.client.ApiException;
import com.decisionlens.client.ApiResponse;
import com.decisionlens.client.Configuration;
import com.decisionlens.client.Pair;
import com.decisionlens.client.ProgressRequestBody;
import com.decisionlens.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.decisionlens.client.model.ErrorResponse;
import com.decisionlens.client.model.Goal;
import com.decisionlens.client.model.Goals;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GoalsApi {
    private ApiClient apiClient;

    public GoalsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public GoalsApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for getGoalsForPortfolio
     * @param portfolioId Portfolio id (required)
     * @param offset Pagination offset (optional)
     * @param limit Pagination limit (optional)
     * @param orderBy Comma delimited list of order by expressions. Use &#39;-&#39; in front of expression for reverse order. (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getGoalsForPortfolioCall(String portfolioId, Integer offset, Integer limit, String orderBy, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/goals";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (portfolioId != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("portfolioId", portfolioId));
        if (offset != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("offset", offset));
        if (limit != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("limit", limit));
        if (orderBy != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("orderBy", orderBy));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "OAuth2" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getGoalsForPortfolioValidateBeforeCall(String portfolioId, Integer offset, Integer limit, String orderBy, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'portfolioId' is set
        if (portfolioId == null) {
            throw new ApiException("Missing the required parameter 'portfolioId' when calling getGoalsForPortfolio(Async)");
        }
        

        com.squareup.okhttp.Call call = getGoalsForPortfolioCall(portfolioId, offset, limit, orderBy, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Get Goals by portfolio id
     * 
     * @param portfolioId Portfolio id (required)
     * @param offset Pagination offset (optional)
     * @param limit Pagination limit (optional)
     * @param orderBy Comma delimited list of order by expressions. Use &#39;-&#39; in front of expression for reverse order. (optional)
     * @return Goals
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Goals getGoalsForPortfolio(String portfolioId, Integer offset, Integer limit, String orderBy) throws ApiException {
        ApiResponse<Goals> resp = getGoalsForPortfolioWithHttpInfo(portfolioId, offset, limit, orderBy);
        return resp.getData();
    }

    /**
     * Get Goals by portfolio id
     * 
     * @param portfolioId Portfolio id (required)
     * @param offset Pagination offset (optional)
     * @param limit Pagination limit (optional)
     * @param orderBy Comma delimited list of order by expressions. Use &#39;-&#39; in front of expression for reverse order. (optional)
     * @return ApiResponse&lt;Goals&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Goals> getGoalsForPortfolioWithHttpInfo(String portfolioId, Integer offset, Integer limit, String orderBy) throws ApiException {
        com.squareup.okhttp.Call call = getGoalsForPortfolioValidateBeforeCall(portfolioId, offset, limit, orderBy, null, null);
        Type localVarReturnType = new TypeToken<Goals>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get Goals by portfolio id (asynchronously)
     * 
     * @param portfolioId Portfolio id (required)
     * @param offset Pagination offset (optional)
     * @param limit Pagination limit (optional)
     * @param orderBy Comma delimited list of order by expressions. Use &#39;-&#39; in front of expression for reverse order. (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getGoalsForPortfolioAsync(String portfolioId, Integer offset, Integer limit, String orderBy, final ApiCallback<Goals> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getGoalsForPortfolioValidateBeforeCall(portfolioId, offset, limit, orderBy, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Goals>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for updateGoalsForPortfolio
     * @param portfolioId Portfolio id (required)
     * @param goals Goals (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call updateGoalsForPortfolioCall(String portfolioId, List<Goal> goals, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = goals;

        // create path and map variables
        String localVarPath = "/goals";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (portfolioId != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("portfolioId", portfolioId));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/merge-patch+json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "OAuth2" };
        return apiClient.buildCall(localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call updateGoalsForPortfolioValidateBeforeCall(String portfolioId, List<Goal> goals, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'portfolioId' is set
        if (portfolioId == null) {
            throw new ApiException("Missing the required parameter 'portfolioId' when calling updateGoalsForPortfolio(Async)");
        }
        
        // verify the required parameter 'goals' is set
        if (goals == null) {
            throw new ApiException("Missing the required parameter 'goals' when calling updateGoalsForPortfolio(Async)");
        }
        

        com.squareup.okhttp.Call call = updateGoalsForPortfolioCall(portfolioId, goals, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Updates Goals for portfolio
     * 
     * @param portfolioId Portfolio id (required)
     * @param goals Goals (required)
     * @return List&lt;Goal&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<Goal> updateGoalsForPortfolio(String portfolioId, List<Goal> goals) throws ApiException {
        ApiResponse<List<Goal>> resp = updateGoalsForPortfolioWithHttpInfo(portfolioId, goals);
        return resp.getData();
    }

    /**
     * Updates Goals for portfolio
     * 
     * @param portfolioId Portfolio id (required)
     * @param goals Goals (required)
     * @return ApiResponse&lt;List&lt;Goal&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<Goal>> updateGoalsForPortfolioWithHttpInfo(String portfolioId, List<Goal> goals) throws ApiException {
        com.squareup.okhttp.Call call = updateGoalsForPortfolioValidateBeforeCall(portfolioId, goals, null, null);
        Type localVarReturnType = new TypeToken<List<Goal>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Updates Goals for portfolio (asynchronously)
     * 
     * @param portfolioId Portfolio id (required)
     * @param goals Goals (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call updateGoalsForPortfolioAsync(String portfolioId, List<Goal> goals, final ApiCallback<List<Goal>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = updateGoalsForPortfolioValidateBeforeCall(portfolioId, goals, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<Goal>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
