/**
 * Decision Lens API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorResponse', 'model/Field', 'model/Fields', 'model/IdeaFormFieldRequest', 'model/Operations', 'model/PatchItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ErrorResponse'), require('../model/Field'), require('../model/Fields'), require('../model/IdeaFormFieldRequest'), require('../model/Operations'), require('../model/PatchItem'));
  } else {
    // Browser globals (root is window)
    if (!root.DecisionLensApi) {
      root.DecisionLensApi = {};
    }
    root.DecisionLensApi.FieldsApi = factory(root.DecisionLensApi.ApiClient, root.DecisionLensApi.ErrorResponse, root.DecisionLensApi.Field, root.DecisionLensApi.Fields, root.DecisionLensApi.IdeaFormFieldRequest, root.DecisionLensApi.Operations, root.DecisionLensApi.PatchItem);
  }
}(this, function(ApiClient, ErrorResponse, Field, Fields, IdeaFormFieldRequest, Operations, PatchItem) {
  'use strict';

  /**
   * Fields service.
   * @module api/FieldsApi
   * @version 1.0
   */

  /**
   * Constructs a new FieldsApi. 
   * @alias module:api/FieldsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createField operation.
     * @callback module:api/FieldsApi~createFieldCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Field>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a new field in a portfolio.
     * @param {module:model/Field} body Field to create
     * @param {Object} opts Optional parameters
     * @param {String} opts.expand JSON string containing an array expand specifications for fields.  An expand specification must have a path and includes optional properties match, unique, allPossible, limit, offset, orderBy.
     * @param {module:api/FieldsApi~createFieldCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Field>}
     */
    this.createField = function(body, opts, callback) {
      opts = opts || {};
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createField");
      }


      var pathParams = {
      };
      var queryParams = {
        'expand': opts['expand'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['OAuth2'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Field];

      return this.apiClient.callApi(
        '/fields', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteField operation.
     * @callback module:api/FieldsApi~deleteFieldCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a field. Also deletes the values for every project.
     * @param {String} id Field id
     * @param {module:api/FieldsApi~deleteFieldCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteField = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteField");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/fields/{id}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getField operation.
     * @callback module:api/FieldsApi~getFieldCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Field} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves a field.
     * @param {String} id Field id
     * @param {Object} opts Optional parameters
     * @param {String} opts.expand JSON string containing an array expand specifications for fields.  An expand specification must have a path and includes optional properties match, unique, allPossible, limit, offset, orderBy.
     * @param {module:api/FieldsApi~getFieldCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Field}
     */
    this.getField = function(id, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getField");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
        'expand': opts['expand'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Field;

      return this.apiClient.callApi(
        '/fields/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getFieldsForPortfolio operation.
     * @callback module:api/FieldsApi~getFieldsForPortfolioCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Fields} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves fields for a portfolio.
     * @param {String} portfolioId Portfolio id
     * @param {Object} opts Optional parameters
     * @param {String} opts.expand JSON string containing an array expand specifications for fields.  An expand specification must have a path and includes optional properties match, unique, allPossible, limit, offset, orderBy.
     * @param {Number} opts.limit Pagination limit
     * @param {Number} opts.offset Pagination offset
     * @param {String} opts.orderBy Comma delimited list of order by expressions. Use &#39;-&#39; in front of expression for reverse order.
     * @param {String} opts.match Semi-colon delimited list of expressions to include in the response only the items in a collections that satisfy the expression(s). All other items should be exluded.
     * @param {module:api/FieldsApi~getFieldsForPortfolioCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Fields}
     */
    this.getFieldsForPortfolio = function(portfolioId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'portfolioId' is set
      if (portfolioId === undefined || portfolioId === null) {
        throw new Error("Missing the required parameter 'portfolioId' when calling getFieldsForPortfolio");
      }


      var pathParams = {
      };
      var queryParams = {
        'portfolioId': portfolioId,
        'expand': opts['expand'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'orderBy': opts['orderBy'],
        'match': opts['match'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Fields;

      return this.apiClient.callApi(
        '/fields', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the setIdeaFormFields operation.
     * @callback module:api/FieldsApi~setIdeaFormFieldsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Field>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Set idea form fields for a portfolio.
     * @param {module:model/IdeaFormFieldRequest} body Idea form field request
     * @param {Object} opts Optional parameters
     * @param {String} opts.expand JSON string containing an array expand specifications for fields.  An expand specification must have a path and includes optional properties match, unique, allPossible, limit, offset, orderBy.
     * @param {module:api/FieldsApi~setIdeaFormFieldsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Field>}
     */
    this.setIdeaFormFields = function(body, opts, callback) {
      opts = opts || {};
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling setIdeaFormFields");
      }


      var pathParams = {
      };
      var queryParams = {
        'expand': opts['expand'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['OAuth2'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Field];

      return this.apiClient.callApi(
        '/fields/ideaForm', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateField operation.
     * @callback module:api/FieldsApi~updateFieldCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Field>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a field utilizing JSON Patch Operations. If the update logic makes changes to other fields, all updated fields will be returned in the response. 
     * @param {String} id Field id
     * @param {module:model/Operations} body JSON Patch Operations to update field.
     * @param {Object} opts Optional parameters
     * @param {String} opts.expand JSON string containing an array expand specifications for fields.  An expand specification must have a path and includes optional properties match, unique, allPossible, limit, offset, orderBy.
     * @param {module:api/FieldsApi~updateFieldCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Field>}
     */
    this.updateField = function(id, body, opts, callback) {
      opts = opts || {};
      var postBody = body;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateField");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateField");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
        'expand': opts['expand'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['OAuth2'];
      var contentTypes = ['application/json-patch+json'];
      var accepts = ['application/json'];
      var returnType = [Field];

      return this.apiClient.callApi(
        '/fields/{id}', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateFields operation.
     * @callback module:api/FieldsApi~updateFieldsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Field>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update fields associated with a portfolio.
     * @param {Array.<module:model/PatchItem>} body JSON Patch Operations to update multiple fields.
     * @param {Object} opts Optional parameters
     * @param {String} opts.expand JSON string containing an array expand specifications for fields.  An expand specification must have a path and includes optional properties match, unique, allPossible, limit, offset, orderBy.
     * @param {module:api/FieldsApi~updateFieldsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Field>}
     */
    this.updateFields = function(body, opts, callback) {
      opts = opts || {};
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateFields");
      }


      var pathParams = {
      };
      var queryParams = {
        'expand': opts['expand'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['OAuth2'];
      var contentTypes = ['application/json-patch+json'];
      var accepts = ['application/json'];
      var returnType = [Field];

      return this.apiClient.callApi(
        '/fields', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
