# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AddAppUsersRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email_ids': 'list[str]',
        'message': 'str',
        'do_not_notify': 'bool',
        'role': 'str'
    }

    attribute_map = {
        'email_ids': 'emailIds',
        'message': 'message',
        'do_not_notify': 'doNotNotify',
        'role': 'role'
    }

    def __init__(self, email_ids=None, message=None, do_not_notify=None, role=None, _check_required=True):  # noqa: E501
        """AddAppUsersRequest - a model defined in Swagger"""  # noqa: E501
        self._email_ids = None
        self._message = None
        self._do_not_notify = None
        self._role = None
        self.discriminator = None
        if email_ids is not None:
            self.email_ids = email_ids
        if message is not None:
            self.message = message
        if do_not_notify is not None:
            self.do_not_notify = do_not_notify
        if role is not None:
            self.role = role

    @property
    def email_ids(self):
        """Gets the email_ids of this AddAppUsersRequest.  # noqa: E501

        Email addresses (usernames) to add to the tenant and grant access to the application.  # noqa: E501

        :return: The email_ids of this AddAppUsersRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._email_ids

    @email_ids.setter
    def email_ids(self, email_ids):
        """Sets the email_ids of this AddAppUsersRequest.

        Email addresses (usernames) to add to the tenant and grant access to the application.  # noqa: E501

        :param email_ids: The email_ids of this AddAppUsersRequest.  # noqa: E501
        :type: list[str]
        """

        self._email_ids = email_ids

    @property
    def message(self):
        """Gets the message of this AddAppUsersRequest.  # noqa: E501

        Optional message for invitation flows where supported.  # noqa: E501

        :return: The message of this AddAppUsersRequest.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this AddAppUsersRequest.

        Optional message for invitation flows where supported.  # noqa: E501

        :param message: The message of this AddAppUsersRequest.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def do_not_notify(self):
        """Gets the do_not_notify of this AddAppUsersRequest.  # noqa: E501

        When true, suppresses registration notification where the underlying user-creation flow allows it.  # noqa: E501

        :return: The do_not_notify of this AddAppUsersRequest.  # noqa: E501
        :rtype: bool
        """
        return self._do_not_notify

    @do_not_notify.setter
    def do_not_notify(self, do_not_notify):
        """Sets the do_not_notify of this AddAppUsersRequest.

        When true, suppresses registration notification where the underlying user-creation flow allows it.  # noqa: E501

        :param do_not_notify: The do_not_notify of this AddAppUsersRequest.  # noqa: E501
        :type: bool
        """

        self._do_not_notify = do_not_notify

    @property
    def role(self):
        """Gets the role of this AddAppUsersRequest.  # noqa: E501

        Initial application role for added users (defaults to APP_VIEWER).  # noqa: E501

        :return: The role of this AddAppUsersRequest.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this AddAppUsersRequest.

        Initial application role for added users (defaults to APP_VIEWER).  # noqa: E501

        :param role: The role of this AddAppUsersRequest.  # noqa: E501
        :type: str
        """

        self._role = role

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AddAppUsersRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddAppUsersRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
