# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from dlxapi.models.field import Field  # noqa: F401,E501

class PrioritizationField(Field):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_system': 'bool',
        'prioritization_id': 'str',
        'portfolio_field_id': 'str',
        'minified_id': 'str'
    }
    if hasattr(Field, "swagger_types"):
        swagger_types.update(Field.swagger_types)

    attribute_map = {
        'is_system': 'isSystem',
        'prioritization_id': 'prioritizationId',
        'portfolio_field_id': 'portfolioFieldId',
        'minified_id': 'minifiedId'
    }
    if hasattr(Field, "attribute_map"):
        attribute_map.update(Field.attribute_map)

    def __init__(self, is_system=None, prioritization_id=None, portfolio_field_id=None, minified_id=None, *args, **kwargs):  # noqa: E501
        """PrioritizationField - a model defined in Swagger"""  # noqa: E501
        self._is_system = None
        self._prioritization_id = None
        self._portfolio_field_id = None
        self._minified_id = None
        self.discriminator = None
        if is_system is not None:
            self.is_system = is_system
        if prioritization_id is not None:
            self.prioritization_id = prioritization_id
        if portfolio_field_id is not None:
            self.portfolio_field_id = portfolio_field_id
        if minified_id is not None:
            self.minified_id = minified_id
        Field.__init__(self, *args, **kwargs)

    @property
    def is_system(self):
        """Gets the is_system of this PrioritizationField.  # noqa: E501


        :return: The is_system of this PrioritizationField.  # noqa: E501
        :rtype: bool
        """
        return self._is_system

    @is_system.setter
    def is_system(self, is_system):
        """Sets the is_system of this PrioritizationField.


        :param is_system: The is_system of this PrioritizationField.  # noqa: E501
        :type: bool
        """

        self._is_system = is_system

    @property
    def prioritization_id(self):
        """Gets the prioritization_id of this PrioritizationField.  # noqa: E501


        :return: The prioritization_id of this PrioritizationField.  # noqa: E501
        :rtype: str
        """
        return self._prioritization_id

    @prioritization_id.setter
    def prioritization_id(self, prioritization_id):
        """Sets the prioritization_id of this PrioritizationField.


        :param prioritization_id: The prioritization_id of this PrioritizationField.  # noqa: E501
        :type: str
        """

        self._prioritization_id = prioritization_id

    @property
    def portfolio_field_id(self):
        """Gets the portfolio_field_id of this PrioritizationField.  # noqa: E501


        :return: The portfolio_field_id of this PrioritizationField.  # noqa: E501
        :rtype: str
        """
        return self._portfolio_field_id

    @portfolio_field_id.setter
    def portfolio_field_id(self, portfolio_field_id):
        """Sets the portfolio_field_id of this PrioritizationField.


        :param portfolio_field_id: The portfolio_field_id of this PrioritizationField.  # noqa: E501
        :type: str
        """

        self._portfolio_field_id = portfolio_field_id

    @property
    def minified_id(self):
        """Gets the minified_id of this PrioritizationField.  # noqa: E501


        :return: The minified_id of this PrioritizationField.  # noqa: E501
        :rtype: str
        """
        return self._minified_id

    @minified_id.setter
    def minified_id(self, minified_id):
        """Sets the minified_id of this PrioritizationField.


        :param minified_id: The minified_id of this PrioritizationField.  # noqa: E501
        :type: str
        """

        self._minified_id = minified_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PrioritizationField, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PrioritizationField):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
