# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PrioritizationIsArchivedUpdatedEvent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'prioritization': 'Prioritization',
        'is_archived': 'bool',
        'previous_is_archived': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'prioritization': 'prioritization',
        'is_archived': 'isArchived',
        'previous_is_archived': 'previousIsArchived'
    }

    def __init__(self, id=None, prioritization=None, is_archived=None, previous_is_archived=None):  # noqa: E501
        """PrioritizationIsArchivedUpdatedEvent - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._prioritization = None
        self._is_archived = None
        self._previous_is_archived = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if prioritization is not None:
            self.prioritization = prioritization
        if is_archived is not None:
            self.is_archived = is_archived
        if previous_is_archived is not None:
            self.previous_is_archived = previous_is_archived

    @property
    def id(self):
        """Gets the id of this PrioritizationIsArchivedUpdatedEvent.  # noqa: E501


        :return: The id of this PrioritizationIsArchivedUpdatedEvent.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PrioritizationIsArchivedUpdatedEvent.


        :param id: The id of this PrioritizationIsArchivedUpdatedEvent.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def prioritization(self):
        """Gets the prioritization of this PrioritizationIsArchivedUpdatedEvent.  # noqa: E501


        :return: The prioritization of this PrioritizationIsArchivedUpdatedEvent.  # noqa: E501
        :rtype: Prioritization
        """
        return self._prioritization

    @prioritization.setter
    def prioritization(self, prioritization):
        """Sets the prioritization of this PrioritizationIsArchivedUpdatedEvent.


        :param prioritization: The prioritization of this PrioritizationIsArchivedUpdatedEvent.  # noqa: E501
        :type: Prioritization
        """

        self._prioritization = prioritization

    @property
    def is_archived(self):
        """Gets the is_archived of this PrioritizationIsArchivedUpdatedEvent.  # noqa: E501


        :return: The is_archived of this PrioritizationIsArchivedUpdatedEvent.  # noqa: E501
        :rtype: bool
        """
        return self._is_archived

    @is_archived.setter
    def is_archived(self, is_archived):
        """Sets the is_archived of this PrioritizationIsArchivedUpdatedEvent.


        :param is_archived: The is_archived of this PrioritizationIsArchivedUpdatedEvent.  # noqa: E501
        :type: bool
        """

        self._is_archived = is_archived

    @property
    def previous_is_archived(self):
        """Gets the previous_is_archived of this PrioritizationIsArchivedUpdatedEvent.  # noqa: E501


        :return: The previous_is_archived of this PrioritizationIsArchivedUpdatedEvent.  # noqa: E501
        :rtype: bool
        """
        return self._previous_is_archived

    @previous_is_archived.setter
    def previous_is_archived(self, previous_is_archived):
        """Sets the previous_is_archived of this PrioritizationIsArchivedUpdatedEvent.


        :param previous_is_archived: The previous_is_archived of this PrioritizationIsArchivedUpdatedEvent.  # noqa: E501
        :type: bool
        """

        self._previous_is_archived = previous_is_archived

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PrioritizationIsArchivedUpdatedEvent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PrioritizationIsArchivedUpdatedEvent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
