# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectChangeRejectedEvent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'portfolio_id': 'str',
        'portfolio_plan': 'PortfolioPlan',
        'project_id': 'str',
        'project_change_id': 'str',
        'project_name': 'str',
        'approval_id': 'str',
        'approver_user_id': 'str',
        'field_id': 'str',
        'field_name': 'str',
        'field_values': 'list[FieldValue]',
        'previous_field_values': 'list[FieldValue]'
    }

    attribute_map = {
        'id': 'id',
        'portfolio_id': 'portfolioId',
        'portfolio_plan': 'portfolioPlan',
        'project_id': 'projectId',
        'project_change_id': 'projectChangeId',
        'project_name': 'projectName',
        'approval_id': 'approvalId',
        'approver_user_id': 'approverUserId',
        'field_id': 'fieldId',
        'field_name': 'fieldName',
        'field_values': 'fieldValues',
        'previous_field_values': 'previousFieldValues'
    }

    def __init__(self, id=None, portfolio_id=None, portfolio_plan=None, project_id=None, project_change_id=None, project_name=None, approval_id=None, approver_user_id=None, field_id=None, field_name=None, field_values=None, previous_field_values=None, _check_required=True):  # noqa: E501
        """ProjectChangeRejectedEvent - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._portfolio_id = None
        self._portfolio_plan = None
        self._project_id = None
        self._project_change_id = None
        self._project_name = None
        self._approval_id = None
        self._approver_user_id = None
        self._field_id = None
        self._field_name = None
        self._field_values = None
        self._previous_field_values = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if portfolio_id is not None:
            self.portfolio_id = portfolio_id
        if portfolio_plan is not None:
            self.portfolio_plan = portfolio_plan
        if project_id is not None:
            self.project_id = project_id
        if project_change_id is not None:
            self.project_change_id = project_change_id
        if project_name is not None:
            self.project_name = project_name
        if approval_id is not None:
            self.approval_id = approval_id
        if approver_user_id is not None:
            self.approver_user_id = approver_user_id
        if field_id is not None:
            self.field_id = field_id
        if field_name is not None:
            self.field_name = field_name
        if field_values is not None:
            self.field_values = field_values
        if previous_field_values is not None:
            self.previous_field_values = previous_field_values

    @property
    def id(self):
        """Gets the id of this ProjectChangeRejectedEvent.  # noqa: E501


        :return: The id of this ProjectChangeRejectedEvent.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProjectChangeRejectedEvent.


        :param id: The id of this ProjectChangeRejectedEvent.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def portfolio_id(self):
        """Gets the portfolio_id of this ProjectChangeRejectedEvent.  # noqa: E501


        :return: The portfolio_id of this ProjectChangeRejectedEvent.  # noqa: E501
        :rtype: str
        """
        return self._portfolio_id

    @portfolio_id.setter
    def portfolio_id(self, portfolio_id):
        """Sets the portfolio_id of this ProjectChangeRejectedEvent.


        :param portfolio_id: The portfolio_id of this ProjectChangeRejectedEvent.  # noqa: E501
        :type: str
        """

        self._portfolio_id = portfolio_id

    @property
    def portfolio_plan(self):
        """Gets the portfolio_plan of this ProjectChangeRejectedEvent.  # noqa: E501


        :return: The portfolio_plan of this ProjectChangeRejectedEvent.  # noqa: E501
        :rtype: PortfolioPlan
        """
        return self._portfolio_plan

    @portfolio_plan.setter
    def portfolio_plan(self, portfolio_plan):
        """Sets the portfolio_plan of this ProjectChangeRejectedEvent.


        :param portfolio_plan: The portfolio_plan of this ProjectChangeRejectedEvent.  # noqa: E501
        :type: PortfolioPlan
        """

        self._portfolio_plan = portfolio_plan

    @property
    def project_id(self):
        """Gets the project_id of this ProjectChangeRejectedEvent.  # noqa: E501


        :return: The project_id of this ProjectChangeRejectedEvent.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this ProjectChangeRejectedEvent.


        :param project_id: The project_id of this ProjectChangeRejectedEvent.  # noqa: E501
        :type: str
        """

        self._project_id = project_id

    @property
    def project_change_id(self):
        """Gets the project_change_id of this ProjectChangeRejectedEvent.  # noqa: E501

        Id of the ProjectChange row this decision resolved. See ProjectChangeApprovedEvent.projectChangeId.   # noqa: E501

        :return: The project_change_id of this ProjectChangeRejectedEvent.  # noqa: E501
        :rtype: str
        """
        return self._project_change_id

    @project_change_id.setter
    def project_change_id(self, project_change_id):
        """Sets the project_change_id of this ProjectChangeRejectedEvent.

        Id of the ProjectChange row this decision resolved. See ProjectChangeApprovedEvent.projectChangeId.   # noqa: E501

        :param project_change_id: The project_change_id of this ProjectChangeRejectedEvent.  # noqa: E501
        :type: str
        """

        self._project_change_id = project_change_id

    @property
    def project_name(self):
        """Gets the project_name of this ProjectChangeRejectedEvent.  # noqa: E501

        Snapshot of the project name at event time so the activity log remains readable after the project is deleted.  # noqa: E501

        :return: The project_name of this ProjectChangeRejectedEvent.  # noqa: E501
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """Sets the project_name of this ProjectChangeRejectedEvent.

        Snapshot of the project name at event time so the activity log remains readable after the project is deleted.  # noqa: E501

        :param project_name: The project_name of this ProjectChangeRejectedEvent.  # noqa: E501
        :type: str
        """

        self._project_name = project_name

    @property
    def approval_id(self):
        """Gets the approval_id of this ProjectChangeRejectedEvent.  # noqa: E501


        :return: The approval_id of this ProjectChangeRejectedEvent.  # noqa: E501
        :rtype: str
        """
        return self._approval_id

    @approval_id.setter
    def approval_id(self, approval_id):
        """Sets the approval_id of this ProjectChangeRejectedEvent.


        :param approval_id: The approval_id of this ProjectChangeRejectedEvent.  # noqa: E501
        :type: str
        """

        self._approval_id = approval_id

    @property
    def approver_user_id(self):
        """Gets the approver_user_id of this ProjectChangeRejectedEvent.  # noqa: E501


        :return: The approver_user_id of this ProjectChangeRejectedEvent.  # noqa: E501
        :rtype: str
        """
        return self._approver_user_id

    @approver_user_id.setter
    def approver_user_id(self, approver_user_id):
        """Sets the approver_user_id of this ProjectChangeRejectedEvent.


        :param approver_user_id: The approver_user_id of this ProjectChangeRejectedEvent.  # noqa: E501
        :type: str
        """

        self._approver_user_id = approver_user_id

    @property
    def field_id(self):
        """Gets the field_id of this ProjectChangeRejectedEvent.  # noqa: E501


        :return: The field_id of this ProjectChangeRejectedEvent.  # noqa: E501
        :rtype: str
        """
        return self._field_id

    @field_id.setter
    def field_id(self, field_id):
        """Sets the field_id of this ProjectChangeRejectedEvent.


        :param field_id: The field_id of this ProjectChangeRejectedEvent.  # noqa: E501
        :type: str
        """

        self._field_id = field_id

    @property
    def field_name(self):
        """Gets the field_name of this ProjectChangeRejectedEvent.  # noqa: E501

        Snapshot of the field name at event time so the activity log remains readable after the field is deleted.  # noqa: E501

        :return: The field_name of this ProjectChangeRejectedEvent.  # noqa: E501
        :rtype: str
        """
        return self._field_name

    @field_name.setter
    def field_name(self, field_name):
        """Sets the field_name of this ProjectChangeRejectedEvent.

        Snapshot of the field name at event time so the activity log remains readable after the field is deleted.  # noqa: E501

        :param field_name: The field_name of this ProjectChangeRejectedEvent.  # noqa: E501
        :type: str
        """

        self._field_name = field_name

    @property
    def field_values(self):
        """Gets the field_values of this ProjectChangeRejectedEvent.  # noqa: E501

        The field values that were rejected.  # noqa: E501

        :return: The field_values of this ProjectChangeRejectedEvent.  # noqa: E501
        :rtype: list[FieldValue]
        """
        return self._field_values

    @field_values.setter
    def field_values(self, field_values):
        """Sets the field_values of this ProjectChangeRejectedEvent.

        The field values that were rejected.  # noqa: E501

        :param field_values: The field_values of this ProjectChangeRejectedEvent.  # noqa: E501
        :type: list[FieldValue]
        """

        self._field_values = field_values

    @property
    def previous_field_values(self):
        """Gets the previous_field_values of this ProjectChangeRejectedEvent.  # noqa: E501

        The field values that existed before the rejected change.  # noqa: E501

        :return: The previous_field_values of this ProjectChangeRejectedEvent.  # noqa: E501
        :rtype: list[FieldValue]
        """
        return self._previous_field_values

    @previous_field_values.setter
    def previous_field_values(self, previous_field_values):
        """Sets the previous_field_values of this ProjectChangeRejectedEvent.

        The field values that existed before the rejected change.  # noqa: E501

        :param previous_field_values: The previous_field_values of this ProjectChangeRejectedEvent.  # noqa: E501
        :type: list[FieldValue]
        """

        self._previous_field_values = previous_field_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectChangeRejectedEvent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectChangeRejectedEvent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
