# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RecommendationRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'portfolio_plan': 'PortfolioPlan',
        'field_ids': 'list[str]',
        'project_ids': 'list[str]'
    }

    attribute_map = {
        'portfolio_plan': 'portfolioPlan',
        'field_ids': 'fieldIds',
        'project_ids': 'projectIds'
    }

    def __init__(self, portfolio_plan=None, field_ids=None, project_ids=None):  # noqa: E501
        """RecommendationRequest - a model defined in Swagger"""  # noqa: E501
        self._portfolio_plan = None
        self._field_ids = None
        self._project_ids = None
        self.discriminator = None
        if portfolio_plan is not None:
            self.portfolio_plan = portfolio_plan
        if field_ids is not None:
            self.field_ids = field_ids
        if project_ids is not None:
            self.project_ids = project_ids

    @property
    def portfolio_plan(self):
        """Gets the portfolio_plan of this RecommendationRequest.  # noqa: E501


        :return: The portfolio_plan of this RecommendationRequest.  # noqa: E501
        :rtype: PortfolioPlan
        """
        return self._portfolio_plan

    @portfolio_plan.setter
    def portfolio_plan(self, portfolio_plan):
        """Sets the portfolio_plan of this RecommendationRequest.


        :param portfolio_plan: The portfolio_plan of this RecommendationRequest.  # noqa: E501
        :type: PortfolioPlan
        """

        self._portfolio_plan = portfolio_plan

    @property
    def field_ids(self):
        """Gets the field_ids of this RecommendationRequest.  # noqa: E501


        :return: The field_ids of this RecommendationRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._field_ids

    @field_ids.setter
    def field_ids(self, field_ids):
        """Sets the field_ids of this RecommendationRequest.


        :param field_ids: The field_ids of this RecommendationRequest.  # noqa: E501
        :type: list[str]
        """

        self._field_ids = field_ids

    @property
    def project_ids(self):
        """Gets the project_ids of this RecommendationRequest.  # noqa: E501


        :return: The project_ids of this RecommendationRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._project_ids

    @project_ids.setter
    def project_ids(self, project_ids):
        """Sets the project_ids of this RecommendationRequest.


        :param project_ids: The project_ids of this RecommendationRequest.  # noqa: E501
        :type: list[str]
        """

        self._project_ids = project_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RecommendationRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RecommendationRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
