/*
 * Decision Lens API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.decisionlens.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.decisionlens.client.model.CategoryOption;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CategoryOptionUpdatedMessagePayload
 */

public class CategoryOptionUpdatedMessagePayload {
  @SerializedName("categoryOption")
  private CategoryOption categoryOption = null;

  public CategoryOptionUpdatedMessagePayload categoryOption(CategoryOption categoryOption) {
    this.categoryOption = categoryOption;
    return this;
  }

   /**
   * Get categoryOption
   * @return categoryOption
  **/
  @ApiModelProperty(required = true, value = "")
  public CategoryOption getCategoryOption() {
    return categoryOption;
  }

  public void setCategoryOption(CategoryOption categoryOption) {
    this.categoryOption = categoryOption;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryOptionUpdatedMessagePayload categoryOptionUpdatedMessagePayload = (CategoryOptionUpdatedMessagePayload) o;
    return Objects.equals(this.categoryOption, categoryOptionUpdatedMessagePayload.categoryOption);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoryOption);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoryOptionUpdatedMessagePayload {\n");
    
    sb.append("    categoryOption: ").append(toIndentedString(categoryOption)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

