/*
 * Decision Lens API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.decisionlens.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.decisionlens.client.model.TemplateProperty;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Mail
 */

public class Mail {
  @SerializedName("from")
  private String from = null;

  @SerializedName("replyTo")
  private String replyTo = null;

  @SerializedName("replyToDisplayName")
  private String replyToDisplayName = null;

  @SerializedName("to")
  private List<String> to = null;

  @SerializedName("cc")
  private List<String> cc = null;

  @SerializedName("bcc")
  private List<String> bcc = null;

  @SerializedName("subject")
  private String subject = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("templateName")
  private String templateName = null;

  @SerializedName("templateProperties")
  private List<TemplateProperty> templateProperties = null;

  public Mail from(String from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  @ApiModelProperty(value = "")
  public String getFrom() {
    return from;
  }

  public void setFrom(String from) {
    this.from = from;
  }

  public Mail replyTo(String replyTo) {
    this.replyTo = replyTo;
    return this;
  }

   /**
   * Get replyTo
   * @return replyTo
  **/
  @ApiModelProperty(value = "")
  public String getReplyTo() {
    return replyTo;
  }

  public void setReplyTo(String replyTo) {
    this.replyTo = replyTo;
  }

  public Mail replyToDisplayName(String replyToDisplayName) {
    this.replyToDisplayName = replyToDisplayName;
    return this;
  }

   /**
   * Get replyToDisplayName
   * @return replyToDisplayName
  **/
  @ApiModelProperty(value = "")
  public String getReplyToDisplayName() {
    return replyToDisplayName;
  }

  public void setReplyToDisplayName(String replyToDisplayName) {
    this.replyToDisplayName = replyToDisplayName;
  }

  public Mail to(List<String> to) {
    this.to = to;
    return this;
  }

  public Mail addToItem(String toItem) {
    if (this.to == null) {
      this.to = new ArrayList<String>();
    }
    this.to.add(toItem);
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @ApiModelProperty(value = "")
  public List<String> getTo() {
    return to;
  }

  public void setTo(List<String> to) {
    this.to = to;
  }

  public Mail cc(List<String> cc) {
    this.cc = cc;
    return this;
  }

  public Mail addCcItem(String ccItem) {
    if (this.cc == null) {
      this.cc = new ArrayList<String>();
    }
    this.cc.add(ccItem);
    return this;
  }

   /**
   * Get cc
   * @return cc
  **/
  @ApiModelProperty(value = "")
  public List<String> getCc() {
    return cc;
  }

  public void setCc(List<String> cc) {
    this.cc = cc;
  }

  public Mail bcc(List<String> bcc) {
    this.bcc = bcc;
    return this;
  }

  public Mail addBccItem(String bccItem) {
    if (this.bcc == null) {
      this.bcc = new ArrayList<String>();
    }
    this.bcc.add(bccItem);
    return this;
  }

   /**
   * Get bcc
   * @return bcc
  **/
  @ApiModelProperty(value = "")
  public List<String> getBcc() {
    return bcc;
  }

  public void setBcc(List<String> bcc) {
    this.bcc = bcc;
  }

  public Mail subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @ApiModelProperty(value = "")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public Mail message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public Mail templateName(String templateName) {
    this.templateName = templateName;
    return this;
  }

   /**
   * Get templateName
   * @return templateName
  **/
  @ApiModelProperty(value = "")
  public String getTemplateName() {
    return templateName;
  }

  public void setTemplateName(String templateName) {
    this.templateName = templateName;
  }

  public Mail templateProperties(List<TemplateProperty> templateProperties) {
    this.templateProperties = templateProperties;
    return this;
  }

  public Mail addTemplatePropertiesItem(TemplateProperty templatePropertiesItem) {
    if (this.templateProperties == null) {
      this.templateProperties = new ArrayList<TemplateProperty>();
    }
    this.templateProperties.add(templatePropertiesItem);
    return this;
  }

   /**
   * Get templateProperties
   * @return templateProperties
  **/
  @ApiModelProperty(value = "")
  public List<TemplateProperty> getTemplateProperties() {
    return templateProperties;
  }

  public void setTemplateProperties(List<TemplateProperty> templateProperties) {
    this.templateProperties = templateProperties;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Mail mail = (Mail) o;
    return Objects.equals(this.from, mail.from) &&
        Objects.equals(this.replyTo, mail.replyTo) &&
        Objects.equals(this.replyToDisplayName, mail.replyToDisplayName) &&
        Objects.equals(this.to, mail.to) &&
        Objects.equals(this.cc, mail.cc) &&
        Objects.equals(this.bcc, mail.bcc) &&
        Objects.equals(this.subject, mail.subject) &&
        Objects.equals(this.message, mail.message) &&
        Objects.equals(this.templateName, mail.templateName) &&
        Objects.equals(this.templateProperties, mail.templateProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, replyTo, replyToDisplayName, to, cc, bcc, subject, message, templateName, templateProperties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Mail {\n");
    
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    replyTo: ").append(toIndentedString(replyTo)).append("\n");
    sb.append("    replyToDisplayName: ").append(toIndentedString(replyToDisplayName)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    cc: ").append(toIndentedString(cc)).append("\n");
    sb.append("    bcc: ").append(toIndentedString(bcc)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    templateName: ").append(toIndentedString(templateName)).append("\n");
    sb.append("    templateProperties: ").append(toIndentedString(templateProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

