/*
 * Decision Lens API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.decisionlens.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.decisionlens.client.model.MinifiedFieldValue;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * MinifiedProject
 */

public class MinifiedProject {
  @SerializedName("id")
  private String id = null;

  @SerializedName("n")
  private String n = null;

  @SerializedName("pos")
  private Integer pos = null;

  @SerializedName("mt")
  private Long mt = null;

  @SerializedName("fvs")
  private Map<String, MinifiedFieldValue> fvs = null;

  @SerializedName("cus")
  private List<String> cus = null;

  public MinifiedProject id(String id) {
    this.id = id;
    return this;
  }

   /**
   * project id
   * @return id
  **/
  @ApiModelProperty(value = "project id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public MinifiedProject n(String n) {
    this.n = n;
    return this;
  }

   /**
   * Project name
   * @return n
  **/
  @ApiModelProperty(value = "Project name")
  public String getN() {
    return n;
  }

  public void setN(String n) {
    this.n = n;
  }

  public MinifiedProject pos(Integer pos) {
    this.pos = pos;
    return this;
  }

   /**
   * Project position
   * @return pos
  **/
  @ApiModelProperty(value = "Project position")
  public Integer getPos() {
    return pos;
  }

  public void setPos(Integer pos) {
    this.pos = pos;
  }

  public MinifiedProject mt(Long mt) {
    this.mt = mt;
    return this;
  }

   /**
   * Project modified time in epoch millis
   * @return mt
  **/
  @ApiModelProperty(value = "Project modified time in epoch millis")
  public Long getMt() {
    return mt;
  }

  public void setMt(Long mt) {
    this.mt = mt;
  }

  public MinifiedProject fvs(Map<String, MinifiedFieldValue> fvs) {
    this.fvs = fvs;
    return this;
  }

  public MinifiedProject putFvsItem(String key, MinifiedFieldValue fvsItem) {
    if (this.fvs == null) {
      this.fvs = new HashMap<String, MinifiedFieldValue>();
    }
    this.fvs.put(key, fvsItem);
    return this;
  }

   /**
   * Minified field values. Key is field index.
   * @return fvs
  **/
  @ApiModelProperty(value = "Minified field values. Key is field index.")
  public Map<String, MinifiedFieldValue> getFvs() {
    return fvs;
  }

  public void setFvs(Map<String, MinifiedFieldValue> fvs) {
    this.fvs = fvs;
  }

  public MinifiedProject cus(List<String> cus) {
    this.cus = cus;
    return this;
  }

  public MinifiedProject addCusItem(String cusItem) {
    if (this.cus == null) {
      this.cus = new ArrayList<String>();
    }
    this.cus.add(cusItem);
    return this;
  }

   /**
   * Get cus
   * @return cus
  **/
  @ApiModelProperty(value = "")
  public List<String> getCus() {
    return cus;
  }

  public void setCus(List<String> cus) {
    this.cus = cus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MinifiedProject minifiedProject = (MinifiedProject) o;
    return Objects.equals(this.id, minifiedProject.id) &&
        Objects.equals(this.n, minifiedProject.n) &&
        Objects.equals(this.pos, minifiedProject.pos) &&
        Objects.equals(this.mt, minifiedProject.mt) &&
        Objects.equals(this.fvs, minifiedProject.fvs) &&
        Objects.equals(this.cus, minifiedProject.cus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, n, pos, mt, fvs, cus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MinifiedProject {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    n: ").append(toIndentedString(n)).append("\n");
    sb.append("    pos: ").append(toIndentedString(pos)).append("\n");
    sb.append("    mt: ").append(toIndentedString(mt)).append("\n");
    sb.append("    fvs: ").append(toIndentedString(fvs)).append("\n");
    sb.append("    cus: ").append(toIndentedString(cus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

