/*
 * Decision Lens API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.decisionlens.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.decisionlens.client.model.Projects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Wiwo
 */

public class Wiwo {
  @SerializedName("inProjects")
  private Projects inProjects = null;

  @SerializedName("outProjects")
  private Projects outProjects = null;

  public Wiwo inProjects(Projects inProjects) {
    this.inProjects = inProjects;
    return this;
  }

   /**
   * Get inProjects
   * @return inProjects
  **/
  @ApiModelProperty(value = "")
  public Projects getInProjects() {
    return inProjects;
  }

  public void setInProjects(Projects inProjects) {
    this.inProjects = inProjects;
  }

  public Wiwo outProjects(Projects outProjects) {
    this.outProjects = outProjects;
    return this;
  }

   /**
   * Get outProjects
   * @return outProjects
  **/
  @ApiModelProperty(value = "")
  public Projects getOutProjects() {
    return outProjects;
  }

  public void setOutProjects(Projects outProjects) {
    this.outProjects = outProjects;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Wiwo wiwo = (Wiwo) o;
    return Objects.equals(this.inProjects, wiwo.inProjects) &&
        Objects.equals(this.outProjects, wiwo.outProjects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inProjects, outProjects);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Wiwo {\n");
    
    sb.append("    inProjects: ").append(toIndentedString(inProjects)).append("\n");
    sb.append("    outProjects: ").append(toIndentedString(outProjects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

