# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.dl_resource import DlResource  # noqa: F401,E501

class Approval(DlResource):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'portfolio_id': 'str',
        'name': 'str',
        'description': 'str',
        'is_active': 'bool',
        'is_open': 'bool',
        'position': 'int',
        'approver_user_ids': 'list[str]',
        'approver_emails': 'list[str]',
        'selectors': 'list[ApprovalSelector]',
        'next_approval_id': 'str',
        'project_change_counts': 'dict(str, int)'
    }
    if hasattr(DlResource, "swagger_types"):
        swagger_types.update(DlResource.swagger_types)

    attribute_map = {
        'portfolio_id': 'portfolioId',
        'name': 'name',
        'description': 'description',
        'is_active': 'isActive',
        'is_open': 'isOpen',
        'position': 'position',
        'approver_user_ids': 'approverUserIds',
        'approver_emails': 'approverEmails',
        'selectors': 'selectors',
        'next_approval_id': 'nextApprovalId',
        'project_change_counts': 'projectChangeCounts'
    }
    if hasattr(DlResource, "attribute_map"):
        attribute_map.update(DlResource.attribute_map)

    def __init__(self, portfolio_id=None, name=None, description=None, is_active=None, is_open=None, position=None, approver_user_ids=None, approver_emails=None, selectors=None, next_approval_id=None, project_change_counts=None, *args, **kwargs):  # noqa: E501
        """Approval - a model defined in Swagger"""  # noqa: E501
        self._portfolio_id = None
        self._name = None
        self._description = None
        self._is_active = None
        self._is_open = None
        self._position = None
        self._approver_user_ids = None
        self._approver_emails = None
        self._selectors = None
        self._next_approval_id = None
        self._project_change_counts = None
        self.discriminator = None
        if portfolio_id is not None:
            self.portfolio_id = portfolio_id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if is_active is not None:
            self.is_active = is_active
        if is_open is not None:
            self.is_open = is_open
        if position is not None:
            self.position = position
        if approver_user_ids is not None:
            self.approver_user_ids = approver_user_ids
        if approver_emails is not None:
            self.approver_emails = approver_emails
        if selectors is not None:
            self.selectors = selectors
        if next_approval_id is not None:
            self.next_approval_id = next_approval_id
        if project_change_counts is not None:
            self.project_change_counts = project_change_counts
        DlResource.__init__(self, *args, **kwargs)

    @property
    def portfolio_id(self):
        """Gets the portfolio_id of this Approval.  # noqa: E501


        :return: The portfolio_id of this Approval.  # noqa: E501
        :rtype: str
        """
        return self._portfolio_id

    @portfolio_id.setter
    def portfolio_id(self, portfolio_id):
        """Sets the portfolio_id of this Approval.


        :param portfolio_id: The portfolio_id of this Approval.  # noqa: E501
        :type: str
        """

        self._portfolio_id = portfolio_id

    @property
    def name(self):
        """Gets the name of this Approval.  # noqa: E501

        Approval name, unique within a portfolio  # noqa: E501

        :return: The name of this Approval.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Approval.

        Approval name, unique within a portfolio  # noqa: E501

        :param name: The name of this Approval.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this Approval.  # noqa: E501


        :return: The description of this Approval.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Approval.


        :param description: The description of this Approval.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def is_active(self):
        """Gets the is_active of this Approval.  # noqa: E501

        When false, the approval is not evaluated. Defaults to false on create.  # noqa: E501

        :return: The is_active of this Approval.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this Approval.

        When false, the approval is not evaluated. Defaults to false on create.  # noqa: E501

        :param is_active: The is_active of this Approval.  # noqa: E501
        :type: bool
        """

        self._is_active = is_active

    @property
    def is_open(self):
        """Gets the is_open of this Approval.  # noqa: E501

        Indicates whether queued edits are available for the assigned approvers to make approve/reject decisions  # noqa: E501

        :return: The is_open of this Approval.  # noqa: E501
        :rtype: bool
        """
        return self._is_open

    @is_open.setter
    def is_open(self, is_open):
        """Sets the is_open of this Approval.

        Indicates whether queued edits are available for the assigned approvers to make approve/reject decisions  # noqa: E501

        :param is_open: The is_open of this Approval.  # noqa: E501
        :type: bool
        """

        self._is_open = is_open

    @property
    def position(self):
        """Gets the position of this Approval.  # noqa: E501

        Read-only. Zero-based precedence order of this workflow within its portfolio, derived from the portfolio's precedence order list. When a project change matches more than one active workflow, the lower position wins. A new workflow is appended last on create; reorder by PATCHing an individual workflow with a /position operation carrying its new index (only the moved workflow is sent, mirroring field / cost-type reorder).  # noqa: E501

        :return: The position of this Approval.  # noqa: E501
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this Approval.

        Read-only. Zero-based precedence order of this workflow within its portfolio, derived from the portfolio's precedence order list. When a project change matches more than one active workflow, the lower position wins. A new workflow is appended last on create; reorder by PATCHing an individual workflow with a /position operation carrying its new index (only the moved workflow is sent, mirroring field / cost-type reorder).  # noqa: E501

        :param position: The position of this Approval.  # noqa: E501
        :type: int
        """

        self._position = position

    @property
    def approver_user_ids(self):
        """Gets the approver_user_ids of this Approval.  # noqa: E501

        Users who must approve  # noqa: E501

        :return: The approver_user_ids of this Approval.  # noqa: E501
        :rtype: list[str]
        """
        return self._approver_user_ids

    @approver_user_ids.setter
    def approver_user_ids(self, approver_user_ids):
        """Sets the approver_user_ids of this Approval.

        Users who must approve  # noqa: E501

        :param approver_user_ids: The approver_user_ids of this Approval.  # noqa: E501
        :type: list[str]
        """

        self._approver_user_ids = approver_user_ids

    @property
    def approver_emails(self):
        """Gets the approver_emails of this Approval.  # noqa: E501

        External approver email addresses (not yet instance users). Each is resolved to an existing instance user or invited, then folded into approverUserIds server-side. Write-only on create/update; never returned.  # noqa: E501

        :return: The approver_emails of this Approval.  # noqa: E501
        :rtype: list[str]
        """
        return self._approver_emails

    @approver_emails.setter
    def approver_emails(self, approver_emails):
        """Sets the approver_emails of this Approval.

        External approver email addresses (not yet instance users). Each is resolved to an existing instance user or invited, then folded into approverUserIds server-side. Write-only on create/update; never returned.  # noqa: E501

        :param approver_emails: The approver_emails of this Approval.  # noqa: E501
        :type: list[str]
        """

        self._approver_emails = approver_emails

    @property
    def selectors(self):
        """Gets the selectors of this Approval.  # noqa: E501

        Selectors evaluated to determine if this approval applies. Match semantics is OR across selectors.  # noqa: E501

        :return: The selectors of this Approval.  # noqa: E501
        :rtype: list[ApprovalSelector]
        """
        return self._selectors

    @selectors.setter
    def selectors(self, selectors):
        """Sets the selectors of this Approval.

        Selectors evaluated to determine if this approval applies. Match semantics is OR across selectors.  # noqa: E501

        :param selectors: The selectors of this Approval.  # noqa: E501
        :type: list[ApprovalSelector]
        """

        self._selectors = selectors

    @property
    def next_approval_id(self):
        """Gets the next_approval_id of this Approval.  # noqa: E501

        Follow-on workflow for a multistage approval. When set, approving a ProjectChange in this workflow does not end its review: the decided row is kept as the stage record and a fresh PENDING copy is created under this workflow for the next sign-off. Reject and move are unaffected — only an approval advances. Null means this is the only (or last) stage; a workflow \"is multistage\" exactly when this is set. The target must belong to the same portfolio and must not close a cycle back to this workflow.   # noqa: E501

        :return: The next_approval_id of this Approval.  # noqa: E501
        :rtype: str
        """
        return self._next_approval_id

    @next_approval_id.setter
    def next_approval_id(self, next_approval_id):
        """Sets the next_approval_id of this Approval.

        Follow-on workflow for a multistage approval. When set, approving a ProjectChange in this workflow does not end its review: the decided row is kept as the stage record and a fresh PENDING copy is created under this workflow for the next sign-off. Reject and move are unaffected — only an approval advances. Null means this is the only (or last) stage; a workflow \"is multistage\" exactly when this is set. The target must belong to the same portfolio and must not close a cycle back to this workflow.   # noqa: E501

        :param next_approval_id: The next_approval_id of this Approval.  # noqa: E501
        :type: str
        """

        self._next_approval_id = next_approval_id

    @property
    def project_change_counts(self):
        """Gets the project_change_counts of this Approval.  # noqa: E501

        Count of associated ProjectChange records keyed by ProjectChangeStatus (PENDING, APPROVED, REJECTED, MOVED). Only populated on GET endpoints; absent on create/update responses.  # noqa: E501

        :return: The project_change_counts of this Approval.  # noqa: E501
        :rtype: dict(str, int)
        """
        return self._project_change_counts

    @project_change_counts.setter
    def project_change_counts(self, project_change_counts):
        """Sets the project_change_counts of this Approval.

        Count of associated ProjectChange records keyed by ProjectChangeStatus (PENDING, APPROVED, REJECTED, MOVED). Only populated on GET endpoints; absent on create/update responses.  # noqa: E501

        :param project_change_counts: The project_change_counts of this Approval.  # noqa: E501
        :type: dict(str, int)
        """

        self._project_change_counts = project_change_counts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Approval, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Approval):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
