# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.dl_resource import DlResource  # noqa: F401,E501

class Field(DlResource):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'original_name': 'str',
        'description': 'str',
        'type': 'FieldType',
        'source': 'Source',
        'portfolio': 'Portfolio',
        'parent': 'Field',
        'position': 'int',
        'type_position': 'int',
        'spend_plan_position': 'int',
        'field_values': 'FieldValues',
        'field_datas': 'FieldDatas',
        'target_type': 'TargetType',
        'data_type': 'DataType',
        'calculation_type': 'CalculationType',
        'is_field_type_approved': 'bool',
        'tag_ids': 'list[str]',
        'category_options': 'CategoryOptions',
        'is_idea_field': 'bool',
        'idea_field_position': 'int',
        'field_requirement': 'FieldRequirement',
        'scale': 'Scale',
        'attributes': 'FieldAttributes',
        'system_description': 'str',
        'cost_type_id': 'str',
        'cost_type_name': 'str',
        'default_cost_type': 'DefaultCostType',
        'field_values_updated_at': 'int'
    }
    if hasattr(DlResource, "swagger_types"):
        swagger_types.update(DlResource.swagger_types)

    attribute_map = {
        'name': 'name',
        'original_name': 'originalName',
        'description': 'description',
        'type': 'type',
        'source': 'source',
        'portfolio': 'portfolio',
        'parent': 'parent',
        'position': 'position',
        'type_position': 'typePosition',
        'spend_plan_position': 'spendPlanPosition',
        'field_values': 'fieldValues',
        'field_datas': 'fieldDatas',
        'target_type': 'targetType',
        'data_type': 'dataType',
        'calculation_type': 'calculationType',
        'is_field_type_approved': 'isFieldTypeApproved',
        'tag_ids': 'tagIds',
        'category_options': 'categoryOptions',
        'is_idea_field': 'isIdeaField',
        'idea_field_position': 'ideaFieldPosition',
        'field_requirement': 'fieldRequirement',
        'scale': 'scale',
        'attributes': 'attributes',
        'system_description': 'systemDescription',
        'cost_type_id': 'costTypeId',
        'cost_type_name': 'costTypeName',
        'default_cost_type': 'defaultCostType',
        'field_values_updated_at': 'fieldValuesUpdatedAt'
    }
    if hasattr(DlResource, "attribute_map"):
        attribute_map.update(DlResource.attribute_map)

    def __init__(self, name=None, original_name=None, description=None, type=None, source=None, portfolio=None, parent=None, position=None, type_position=None, spend_plan_position=None, field_values=None, field_datas=None, target_type=None, data_type=None, calculation_type=None, is_field_type_approved=None, tag_ids=None, category_options=None, is_idea_field=None, idea_field_position=None, field_requirement=None, scale=None, attributes=None, system_description=None, cost_type_id=None, cost_type_name=None, default_cost_type=None, field_values_updated_at=None, _check_required=True, *args, **kwargs):  # noqa: E501
        """Field - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._original_name = None
        self._description = None
        self._type = None
        self._source = None
        self._portfolio = None
        self._parent = None
        self._position = None
        self._type_position = None
        self._spend_plan_position = None
        self._field_values = None
        self._field_datas = None
        self._target_type = None
        self._data_type = None
        self._calculation_type = None
        self._is_field_type_approved = None
        self._tag_ids = None
        self._category_options = None
        self._is_idea_field = None
        self._idea_field_position = None
        self._field_requirement = None
        self._scale = None
        self._attributes = None
        self._system_description = None
        self._cost_type_id = None
        self._cost_type_name = None
        self._default_cost_type = None
        self._field_values_updated_at = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if original_name is not None:
            self.original_name = original_name
        if description is not None:
            self.description = description
        if type is not None:
            self.type = type
        if source is not None:
            self.source = source
        if portfolio is not None:
            self.portfolio = portfolio
        if parent is not None:
            self.parent = parent
        if position is not None:
            self.position = position
        if type_position is not None:
            self.type_position = type_position
        if spend_plan_position is not None:
            self.spend_plan_position = spend_plan_position
        if field_values is not None:
            self.field_values = field_values
        if field_datas is not None:
            self.field_datas = field_datas
        if target_type is not None:
            self.target_type = target_type
        if data_type is not None:
            self.data_type = data_type
        if calculation_type is not None:
            self.calculation_type = calculation_type
        if is_field_type_approved is not None:
            self.is_field_type_approved = is_field_type_approved
        if tag_ids is not None:
            self.tag_ids = tag_ids
        if category_options is not None:
            self.category_options = category_options
        if is_idea_field is not None:
            self.is_idea_field = is_idea_field
        if idea_field_position is not None:
            self.idea_field_position = idea_field_position
        if field_requirement is not None:
            self.field_requirement = field_requirement
        if scale is not None:
            self.scale = scale
        if attributes is not None:
            self.attributes = attributes
        if system_description is not None:
            self.system_description = system_description
        if cost_type_id is not None:
            self.cost_type_id = cost_type_id
        if cost_type_name is not None:
            self.cost_type_name = cost_type_name
        if default_cost_type is not None:
            self.default_cost_type = default_cost_type
        if field_values_updated_at is not None:
            self.field_values_updated_at = field_values_updated_at
        DlResource.__init__(self, *args, _check_required=_check_required, **kwargs)

    @property
    def name(self):
        """Gets the name of this Field.  # noqa: E501


        :return: The name of this Field.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Field.


        :param name: The name of this Field.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def original_name(self):
        """Gets the original_name of this Field.  # noqa: E501


        :return: The original_name of this Field.  # noqa: E501
        :rtype: str
        """
        return self._original_name

    @original_name.setter
    def original_name(self, original_name):
        """Sets the original_name of this Field.


        :param original_name: The original_name of this Field.  # noqa: E501
        :type: str
        """

        self._original_name = original_name

    @property
    def description(self):
        """Gets the description of this Field.  # noqa: E501


        :return: The description of this Field.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Field.


        :param description: The description of this Field.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def type(self):
        """Gets the type of this Field.  # noqa: E501


        :return: The type of this Field.  # noqa: E501
        :rtype: FieldType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Field.


        :param type: The type of this Field.  # noqa: E501
        :type: FieldType
        """

        self._type = type

    @property
    def source(self):
        """Gets the source of this Field.  # noqa: E501


        :return: The source of this Field.  # noqa: E501
        :rtype: Source
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this Field.


        :param source: The source of this Field.  # noqa: E501
        :type: Source
        """

        self._source = source

    @property
    def portfolio(self):
        """Gets the portfolio of this Field.  # noqa: E501


        :return: The portfolio of this Field.  # noqa: E501
        :rtype: Portfolio
        """
        return self._portfolio

    @portfolio.setter
    def portfolio(self, portfolio):
        """Sets the portfolio of this Field.


        :param portfolio: The portfolio of this Field.  # noqa: E501
        :type: Portfolio
        """

        self._portfolio = portfolio

    @property
    def parent(self):
        """Gets the parent of this Field.  # noqa: E501


        :return: The parent of this Field.  # noqa: E501
        :rtype: Field
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this Field.


        :param parent: The parent of this Field.  # noqa: E501
        :type: Field
        """

        self._parent = parent

    @property
    def position(self):
        """Gets the position of this Field.  # noqa: E501


        :return: The position of this Field.  # noqa: E501
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this Field.


        :param position: The position of this Field.  # noqa: E501
        :type: int
        """

        self._position = position

    @property
    def type_position(self):
        """Gets the type_position of this Field.  # noqa: E501


        :return: The type_position of this Field.  # noqa: E501
        :rtype: int
        """
        return self._type_position

    @type_position.setter
    def type_position(self, type_position):
        """Sets the type_position of this Field.


        :param type_position: The type_position of this Field.  # noqa: E501
        :type: int
        """

        self._type_position = type_position

    @property
    def spend_plan_position(self):
        """Gets the spend_plan_position of this Field.  # noqa: E501


        :return: The spend_plan_position of this Field.  # noqa: E501
        :rtype: int
        """
        return self._spend_plan_position

    @spend_plan_position.setter
    def spend_plan_position(self, spend_plan_position):
        """Sets the spend_plan_position of this Field.


        :param spend_plan_position: The spend_plan_position of this Field.  # noqa: E501
        :type: int
        """

        self._spend_plan_position = spend_plan_position

    @property
    def field_values(self):
        """Gets the field_values of this Field.  # noqa: E501


        :return: The field_values of this Field.  # noqa: E501
        :rtype: FieldValues
        """
        return self._field_values

    @field_values.setter
    def field_values(self, field_values):
        """Sets the field_values of this Field.


        :param field_values: The field_values of this Field.  # noqa: E501
        :type: FieldValues
        """

        self._field_values = field_values

    @property
    def field_datas(self):
        """Gets the field_datas of this Field.  # noqa: E501


        :return: The field_datas of this Field.  # noqa: E501
        :rtype: FieldDatas
        """
        return self._field_datas

    @field_datas.setter
    def field_datas(self, field_datas):
        """Sets the field_datas of this Field.


        :param field_datas: The field_datas of this Field.  # noqa: E501
        :type: FieldDatas
        """

        self._field_datas = field_datas

    @property
    def target_type(self):
        """Gets the target_type of this Field.  # noqa: E501


        :return: The target_type of this Field.  # noqa: E501
        :rtype: TargetType
        """
        return self._target_type

    @target_type.setter
    def target_type(self, target_type):
        """Sets the target_type of this Field.


        :param target_type: The target_type of this Field.  # noqa: E501
        :type: TargetType
        """

        self._target_type = target_type

    @property
    def data_type(self):
        """Gets the data_type of this Field.  # noqa: E501


        :return: The data_type of this Field.  # noqa: E501
        :rtype: DataType
        """
        return self._data_type

    @data_type.setter
    def data_type(self, data_type):
        """Sets the data_type of this Field.


        :param data_type: The data_type of this Field.  # noqa: E501
        :type: DataType
        """

        self._data_type = data_type

    @property
    def calculation_type(self):
        """Gets the calculation_type of this Field.  # noqa: E501


        :return: The calculation_type of this Field.  # noqa: E501
        :rtype: CalculationType
        """
        return self._calculation_type

    @calculation_type.setter
    def calculation_type(self, calculation_type):
        """Sets the calculation_type of this Field.


        :param calculation_type: The calculation_type of this Field.  # noqa: E501
        :type: CalculationType
        """

        self._calculation_type = calculation_type

    @property
    def is_field_type_approved(self):
        """Gets the is_field_type_approved of this Field.  # noqa: E501


        :return: The is_field_type_approved of this Field.  # noqa: E501
        :rtype: bool
        """
        return self._is_field_type_approved

    @is_field_type_approved.setter
    def is_field_type_approved(self, is_field_type_approved):
        """Sets the is_field_type_approved of this Field.


        :param is_field_type_approved: The is_field_type_approved of this Field.  # noqa: E501
        :type: bool
        """

        self._is_field_type_approved = is_field_type_approved

    @property
    def tag_ids(self):
        """Gets the tag_ids of this Field.  # noqa: E501


        :return: The tag_ids of this Field.  # noqa: E501
        :rtype: list[str]
        """
        return self._tag_ids

    @tag_ids.setter
    def tag_ids(self, tag_ids):
        """Sets the tag_ids of this Field.


        :param tag_ids: The tag_ids of this Field.  # noqa: E501
        :type: list[str]
        """

        self._tag_ids = tag_ids

    @property
    def category_options(self):
        """Gets the category_options of this Field.  # noqa: E501


        :return: The category_options of this Field.  # noqa: E501
        :rtype: CategoryOptions
        """
        return self._category_options

    @category_options.setter
    def category_options(self, category_options):
        """Sets the category_options of this Field.


        :param category_options: The category_options of this Field.  # noqa: E501
        :type: CategoryOptions
        """

        self._category_options = category_options

    @property
    def is_idea_field(self):
        """Gets the is_idea_field of this Field.  # noqa: E501


        :return: The is_idea_field of this Field.  # noqa: E501
        :rtype: bool
        """
        return self._is_idea_field

    @is_idea_field.setter
    def is_idea_field(self, is_idea_field):
        """Sets the is_idea_field of this Field.


        :param is_idea_field: The is_idea_field of this Field.  # noqa: E501
        :type: bool
        """

        self._is_idea_field = is_idea_field

    @property
    def idea_field_position(self):
        """Gets the idea_field_position of this Field.  # noqa: E501


        :return: The idea_field_position of this Field.  # noqa: E501
        :rtype: int
        """
        return self._idea_field_position

    @idea_field_position.setter
    def idea_field_position(self, idea_field_position):
        """Sets the idea_field_position of this Field.


        :param idea_field_position: The idea_field_position of this Field.  # noqa: E501
        :type: int
        """

        self._idea_field_position = idea_field_position

    @property
    def field_requirement(self):
        """Gets the field_requirement of this Field.  # noqa: E501


        :return: The field_requirement of this Field.  # noqa: E501
        :rtype: FieldRequirement
        """
        return self._field_requirement

    @field_requirement.setter
    def field_requirement(self, field_requirement):
        """Sets the field_requirement of this Field.


        :param field_requirement: The field_requirement of this Field.  # noqa: E501
        :type: FieldRequirement
        """

        self._field_requirement = field_requirement

    @property
    def scale(self):
        """Gets the scale of this Field.  # noqa: E501


        :return: The scale of this Field.  # noqa: E501
        :rtype: Scale
        """
        return self._scale

    @scale.setter
    def scale(self, scale):
        """Sets the scale of this Field.


        :param scale: The scale of this Field.  # noqa: E501
        :type: Scale
        """

        self._scale = scale

    @property
    def attributes(self):
        """Gets the attributes of this Field.  # noqa: E501


        :return: The attributes of this Field.  # noqa: E501
        :rtype: FieldAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this Field.


        :param attributes: The attributes of this Field.  # noqa: E501
        :type: FieldAttributes
        """

        self._attributes = attributes

    @property
    def system_description(self):
        """Gets the system_description of this Field.  # noqa: E501


        :return: The system_description of this Field.  # noqa: E501
        :rtype: str
        """
        return self._system_description

    @system_description.setter
    def system_description(self, system_description):
        """Sets the system_description of this Field.


        :param system_description: The system_description of this Field.  # noqa: E501
        :type: str
        """

        self._system_description = system_description

    @property
    def cost_type_id(self):
        """Gets the cost_type_id of this Field.  # noqa: E501


        :return: The cost_type_id of this Field.  # noqa: E501
        :rtype: str
        """
        return self._cost_type_id

    @cost_type_id.setter
    def cost_type_id(self, cost_type_id):
        """Sets the cost_type_id of this Field.


        :param cost_type_id: The cost_type_id of this Field.  # noqa: E501
        :type: str
        """

        self._cost_type_id = cost_type_id

    @property
    def cost_type_name(self):
        """Gets the cost_type_name of this Field.  # noqa: E501


        :return: The cost_type_name of this Field.  # noqa: E501
        :rtype: str
        """
        return self._cost_type_name

    @cost_type_name.setter
    def cost_type_name(self, cost_type_name):
        """Sets the cost_type_name of this Field.


        :param cost_type_name: The cost_type_name of this Field.  # noqa: E501
        :type: str
        """

        self._cost_type_name = cost_type_name

    @property
    def default_cost_type(self):
        """Gets the default_cost_type of this Field.  # noqa: E501


        :return: The default_cost_type of this Field.  # noqa: E501
        :rtype: DefaultCostType
        """
        return self._default_cost_type

    @default_cost_type.setter
    def default_cost_type(self, default_cost_type):
        """Sets the default_cost_type of this Field.


        :param default_cost_type: The default_cost_type of this Field.  # noqa: E501
        :type: DefaultCostType
        """

        self._default_cost_type = default_cost_type

    @property
    def field_values_updated_at(self):
        """Gets the field_values_updated_at of this Field.  # noqa: E501


        :return: The field_values_updated_at of this Field.  # noqa: E501
        :rtype: int
        """
        return self._field_values_updated_at

    @field_values_updated_at.setter
    def field_values_updated_at(self, field_values_updated_at):
        """Sets the field_values_updated_at of this Field.


        :param field_values_updated_at: The field_values_updated_at of this Field.  # noqa: E501
        :type: int
        """

        self._field_values_updated_at = field_values_updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Field, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Field):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
