# coding: utf-8

"""
    Decision Lens API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FieldCreatedEvent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source_id': 'str',
        'parent': 'Field',
        'is_field_type_approved': 'bool',
        'type_position': 'int',
        'data_type': 'DataType',
        'target_type': 'TargetType',
        'is_from_import': 'bool',
        'original_name': 'str',
        'is_idea_field': 'bool',
        'field_requirement': 'FieldRequirement',
        'portfolio_id': 'str',
        'cost_type': 'CostType',
        'name': 'str',
        'is_grouped': 'bool',
        'id': 'str',
        'position': 'int',
        'category_options': 'CategoryOptions',
        'idea_field_position': 'int',
        'field_type': 'FieldType',
        'portfolio_plan': 'PortfolioPlan'
    }

    attribute_map = {
        'source_id': 'sourceId',
        'parent': 'parent',
        'is_field_type_approved': 'isFieldTypeApproved',
        'type_position': 'typePosition',
        'data_type': 'dataType',
        'target_type': 'targetType',
        'is_from_import': 'isFromImport',
        'original_name': 'originalName',
        'is_idea_field': 'isIdeaField',
        'field_requirement': 'fieldRequirement',
        'portfolio_id': 'portfolioId',
        'cost_type': 'costType',
        'name': 'name',
        'is_grouped': 'isGrouped',
        'id': 'id',
        'position': 'position',
        'category_options': 'categoryOptions',
        'idea_field_position': 'ideaFieldPosition',
        'field_type': 'fieldType',
        'portfolio_plan': 'portfolioPlan'
    }

    def __init__(self, source_id=None, parent=None, is_field_type_approved=None, type_position=None, data_type=None, target_type=None, is_from_import=None, original_name=None, is_idea_field=None, field_requirement=None, portfolio_id=None, cost_type=None, name=None, is_grouped=None, id=None, position=None, category_options=None, idea_field_position=None, field_type=None, portfolio_plan=None):  # noqa: E501
        """FieldCreatedEvent - a model defined in Swagger"""  # noqa: E501
        self._source_id = None
        self._parent = None
        self._is_field_type_approved = None
        self._type_position = None
        self._data_type = None
        self._target_type = None
        self._is_from_import = None
        self._original_name = None
        self._is_idea_field = None
        self._field_requirement = None
        self._portfolio_id = None
        self._cost_type = None
        self._name = None
        self._is_grouped = None
        self._id = None
        self._position = None
        self._category_options = None
        self._idea_field_position = None
        self._field_type = None
        self._portfolio_plan = None
        self.discriminator = None
        if source_id is not None:
            self.source_id = source_id
        if parent is not None:
            self.parent = parent
        if is_field_type_approved is not None:
            self.is_field_type_approved = is_field_type_approved
        if type_position is not None:
            self.type_position = type_position
        if data_type is not None:
            self.data_type = data_type
        if target_type is not None:
            self.target_type = target_type
        if is_from_import is not None:
            self.is_from_import = is_from_import
        if original_name is not None:
            self.original_name = original_name
        if is_idea_field is not None:
            self.is_idea_field = is_idea_field
        if field_requirement is not None:
            self.field_requirement = field_requirement
        if portfolio_id is not None:
            self.portfolio_id = portfolio_id
        if cost_type is not None:
            self.cost_type = cost_type
        if name is not None:
            self.name = name
        if is_grouped is not None:
            self.is_grouped = is_grouped
        if id is not None:
            self.id = id
        if position is not None:
            self.position = position
        if category_options is not None:
            self.category_options = category_options
        if idea_field_position is not None:
            self.idea_field_position = idea_field_position
        if field_type is not None:
            self.field_type = field_type
        if portfolio_plan is not None:
            self.portfolio_plan = portfolio_plan

    @property
    def source_id(self):
        """Gets the source_id of this FieldCreatedEvent.  # noqa: E501


        :return: The source_id of this FieldCreatedEvent.  # noqa: E501
        :rtype: str
        """
        return self._source_id

    @source_id.setter
    def source_id(self, source_id):
        """Sets the source_id of this FieldCreatedEvent.


        :param source_id: The source_id of this FieldCreatedEvent.  # noqa: E501
        :type: str
        """

        self._source_id = source_id

    @property
    def parent(self):
        """Gets the parent of this FieldCreatedEvent.  # noqa: E501


        :return: The parent of this FieldCreatedEvent.  # noqa: E501
        :rtype: Field
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this FieldCreatedEvent.


        :param parent: The parent of this FieldCreatedEvent.  # noqa: E501
        :type: Field
        """

        self._parent = parent

    @property
    def is_field_type_approved(self):
        """Gets the is_field_type_approved of this FieldCreatedEvent.  # noqa: E501


        :return: The is_field_type_approved of this FieldCreatedEvent.  # noqa: E501
        :rtype: bool
        """
        return self._is_field_type_approved

    @is_field_type_approved.setter
    def is_field_type_approved(self, is_field_type_approved):
        """Sets the is_field_type_approved of this FieldCreatedEvent.


        :param is_field_type_approved: The is_field_type_approved of this FieldCreatedEvent.  # noqa: E501
        :type: bool
        """

        self._is_field_type_approved = is_field_type_approved

    @property
    def type_position(self):
        """Gets the type_position of this FieldCreatedEvent.  # noqa: E501


        :return: The type_position of this FieldCreatedEvent.  # noqa: E501
        :rtype: int
        """
        return self._type_position

    @type_position.setter
    def type_position(self, type_position):
        """Sets the type_position of this FieldCreatedEvent.


        :param type_position: The type_position of this FieldCreatedEvent.  # noqa: E501
        :type: int
        """

        self._type_position = type_position

    @property
    def data_type(self):
        """Gets the data_type of this FieldCreatedEvent.  # noqa: E501


        :return: The data_type of this FieldCreatedEvent.  # noqa: E501
        :rtype: DataType
        """
        return self._data_type

    @data_type.setter
    def data_type(self, data_type):
        """Sets the data_type of this FieldCreatedEvent.


        :param data_type: The data_type of this FieldCreatedEvent.  # noqa: E501
        :type: DataType
        """

        self._data_type = data_type

    @property
    def target_type(self):
        """Gets the target_type of this FieldCreatedEvent.  # noqa: E501


        :return: The target_type of this FieldCreatedEvent.  # noqa: E501
        :rtype: TargetType
        """
        return self._target_type

    @target_type.setter
    def target_type(self, target_type):
        """Sets the target_type of this FieldCreatedEvent.


        :param target_type: The target_type of this FieldCreatedEvent.  # noqa: E501
        :type: TargetType
        """

        self._target_type = target_type

    @property
    def is_from_import(self):
        """Gets the is_from_import of this FieldCreatedEvent.  # noqa: E501


        :return: The is_from_import of this FieldCreatedEvent.  # noqa: E501
        :rtype: bool
        """
        return self._is_from_import

    @is_from_import.setter
    def is_from_import(self, is_from_import):
        """Sets the is_from_import of this FieldCreatedEvent.


        :param is_from_import: The is_from_import of this FieldCreatedEvent.  # noqa: E501
        :type: bool
        """

        self._is_from_import = is_from_import

    @property
    def original_name(self):
        """Gets the original_name of this FieldCreatedEvent.  # noqa: E501


        :return: The original_name of this FieldCreatedEvent.  # noqa: E501
        :rtype: str
        """
        return self._original_name

    @original_name.setter
    def original_name(self, original_name):
        """Sets the original_name of this FieldCreatedEvent.


        :param original_name: The original_name of this FieldCreatedEvent.  # noqa: E501
        :type: str
        """

        self._original_name = original_name

    @property
    def is_idea_field(self):
        """Gets the is_idea_field of this FieldCreatedEvent.  # noqa: E501


        :return: The is_idea_field of this FieldCreatedEvent.  # noqa: E501
        :rtype: bool
        """
        return self._is_idea_field

    @is_idea_field.setter
    def is_idea_field(self, is_idea_field):
        """Sets the is_idea_field of this FieldCreatedEvent.


        :param is_idea_field: The is_idea_field of this FieldCreatedEvent.  # noqa: E501
        :type: bool
        """

        self._is_idea_field = is_idea_field

    @property
    def field_requirement(self):
        """Gets the field_requirement of this FieldCreatedEvent.  # noqa: E501


        :return: The field_requirement of this FieldCreatedEvent.  # noqa: E501
        :rtype: FieldRequirement
        """
        return self._field_requirement

    @field_requirement.setter
    def field_requirement(self, field_requirement):
        """Sets the field_requirement of this FieldCreatedEvent.


        :param field_requirement: The field_requirement of this FieldCreatedEvent.  # noqa: E501
        :type: FieldRequirement
        """

        self._field_requirement = field_requirement

    @property
    def portfolio_id(self):
        """Gets the portfolio_id of this FieldCreatedEvent.  # noqa: E501


        :return: The portfolio_id of this FieldCreatedEvent.  # noqa: E501
        :rtype: str
        """
        return self._portfolio_id

    @portfolio_id.setter
    def portfolio_id(self, portfolio_id):
        """Sets the portfolio_id of this FieldCreatedEvent.


        :param portfolio_id: The portfolio_id of this FieldCreatedEvent.  # noqa: E501
        :type: str
        """

        self._portfolio_id = portfolio_id

    @property
    def cost_type(self):
        """Gets the cost_type of this FieldCreatedEvent.  # noqa: E501


        :return: The cost_type of this FieldCreatedEvent.  # noqa: E501
        :rtype: CostType
        """
        return self._cost_type

    @cost_type.setter
    def cost_type(self, cost_type):
        """Sets the cost_type of this FieldCreatedEvent.


        :param cost_type: The cost_type of this FieldCreatedEvent.  # noqa: E501
        :type: CostType
        """

        self._cost_type = cost_type

    @property
    def name(self):
        """Gets the name of this FieldCreatedEvent.  # noqa: E501


        :return: The name of this FieldCreatedEvent.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FieldCreatedEvent.


        :param name: The name of this FieldCreatedEvent.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def is_grouped(self):
        """Gets the is_grouped of this FieldCreatedEvent.  # noqa: E501


        :return: The is_grouped of this FieldCreatedEvent.  # noqa: E501
        :rtype: bool
        """
        return self._is_grouped

    @is_grouped.setter
    def is_grouped(self, is_grouped):
        """Sets the is_grouped of this FieldCreatedEvent.


        :param is_grouped: The is_grouped of this FieldCreatedEvent.  # noqa: E501
        :type: bool
        """

        self._is_grouped = is_grouped

    @property
    def id(self):
        """Gets the id of this FieldCreatedEvent.  # noqa: E501


        :return: The id of this FieldCreatedEvent.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FieldCreatedEvent.


        :param id: The id of this FieldCreatedEvent.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def position(self):
        """Gets the position of this FieldCreatedEvent.  # noqa: E501


        :return: The position of this FieldCreatedEvent.  # noqa: E501
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this FieldCreatedEvent.


        :param position: The position of this FieldCreatedEvent.  # noqa: E501
        :type: int
        """

        self._position = position

    @property
    def category_options(self):
        """Gets the category_options of this FieldCreatedEvent.  # noqa: E501


        :return: The category_options of this FieldCreatedEvent.  # noqa: E501
        :rtype: CategoryOptions
        """
        return self._category_options

    @category_options.setter
    def category_options(self, category_options):
        """Sets the category_options of this FieldCreatedEvent.


        :param category_options: The category_options of this FieldCreatedEvent.  # noqa: E501
        :type: CategoryOptions
        """

        self._category_options = category_options

    @property
    def idea_field_position(self):
        """Gets the idea_field_position of this FieldCreatedEvent.  # noqa: E501


        :return: The idea_field_position of this FieldCreatedEvent.  # noqa: E501
        :rtype: int
        """
        return self._idea_field_position

    @idea_field_position.setter
    def idea_field_position(self, idea_field_position):
        """Sets the idea_field_position of this FieldCreatedEvent.


        :param idea_field_position: The idea_field_position of this FieldCreatedEvent.  # noqa: E501
        :type: int
        """

        self._idea_field_position = idea_field_position

    @property
    def field_type(self):
        """Gets the field_type of this FieldCreatedEvent.  # noqa: E501


        :return: The field_type of this FieldCreatedEvent.  # noqa: E501
        :rtype: FieldType
        """
        return self._field_type

    @field_type.setter
    def field_type(self, field_type):
        """Sets the field_type of this FieldCreatedEvent.


        :param field_type: The field_type of this FieldCreatedEvent.  # noqa: E501
        :type: FieldType
        """

        self._field_type = field_type

    @property
    def portfolio_plan(self):
        """Gets the portfolio_plan of this FieldCreatedEvent.  # noqa: E501


        :return: The portfolio_plan of this FieldCreatedEvent.  # noqa: E501
        :rtype: PortfolioPlan
        """
        return self._portfolio_plan

    @portfolio_plan.setter
    def portfolio_plan(self, portfolio_plan):
        """Sets the portfolio_plan of this FieldCreatedEvent.


        :param portfolio_plan: The portfolio_plan of this FieldCreatedEvent.  # noqa: E501
        :type: PortfolioPlan
        """

        self._portfolio_plan = portfolio_plan

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FieldCreatedEvent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FieldCreatedEvent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
